### ISSUE TITLE
Auth Schemes should support Docs

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#1035]
```
name: api
auth: HeaderAuthentication
auth-schemes:
  HeaderAuthentication: 
    header: Authentication 
    type: string
    docs: An API key is a token that you provide when making API calls.
```

Upon running `fern check`: 
```
api.yml -> auth-schemes -> HeaderAuthentication
Unexpected key
Encountered unexpected key docs
```
