### ISSUE TITLE
Optional tag -> question mark (?)

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#106]
*tip?: double*         instead of          *tip: optional< double >*

Easier readability, follows typescript convention

**Comment by dsinghvi** [comment]
Closing for now since this doesn't seem necessary

**Comment by zachkirsch** [comment]
God I would love this, and `[]` for lists

**Comment by dannysheridan** [comment]
+1 for this right now

```
        query-parameters:
          id: optional<list<event.EventId>>
          webhook_id: optional<list<connection.ConnectionId>>
          source_id: optional<list<source.SourceId>>
          destination_id: optional<list<destination.DestinationId>>
          cli_id: optional<list<CliId>>
          status: optional<RequestStatus>
          response_status: optional<integer>
```
