### ISSUE TITLE
Set up Dependabot for generators.yml and fern.config.json

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#1071]
As a user, I want to install the `dependabot` app and have a notification that a new version of the fern cli or any generator I'm using is now available.

**Comment by dannysheridan** [comment]
ChatGPT:

If you are using a custom file format for specifying dependencies, such as your generators.yml file, you may need to teach Dependabot how to understand and update these dependencies. You can do this by creating a configuration file for Dependabot, called a .dependabot/config.yml, in the root of your repository.

In the configuration file, you can specify rules and patterns for Dependabot to follow when searching for and updating dependencies in your custom file. For example, you might specify the file path of your generators.yml file and the specific field or fields that contain the dependencies you want Dependabot to update. You can also specify the type of update you want Dependabot to perform (e.g. patch, minor, or major) and the range of versions that Dependabot should consider when searching for updates.

Here is an example of what your .dependabot/config.yml file might look like for updating the dependencies in your generators.yml file:

```
version: 2
update_configs:
  - package_manager: custom
    directory: '/'
    update_schedule: daily
    file:
      - path: generators.yml
        dependencies:
          - name: '*'
            version: '*'
            update_type: patch
```
