### ISSUE TITLE
Document allow multiple for query parameters

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#1087]
```
query-parameters:
    provider_ids:
        type: optional<uuid>
        allow-multiple: true
```
