### ISSUE TITLE
I can't add docs to a request

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#1126]
Within a request, I have docs. Fern doesn't allow me to add them.

```
searchIdentities:
          method: GET  
          path: /search 
          request: 
            docs: The query to match identity display names and account numbers against.
            name: SearchIdentitiesInput
            query-parameters:
              query: string 
```

**Comment by zachkirsch** [comment]
You can't add docs to the request, but you can add docs to the request body

```
searchIdentities:
          method: GET  
          path: /search 
          request: 
            docs: The query to match identity display names and account numbers against.
            name: SearchIdentitiesInput
            query-parameters:
              query: string 
            body:
              docs: ...
              ...
```

does that work?
