### ISSUE TITLE
Support generics in spec

### ISSUE THREAD

**Issue by zachkirsch** [fern-api/fern#1146]
There are some cases where it’d be helpful to define generics so you can reuse types. 

For example:

```yaml
UpdateableField<T>:
  union:
    noUpdate: {}
    newValue: T
```

One thing we’d have to make sure is that it worked with all the programming languages / frameworks. (e.g. does pydantic play nicely with generic models? Does fastapi?)
