### ISSUE TITLE
Add enum examples with different name and value

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#1181]
In docs, we should have an example where an enum has a name and value (and they're different).

**Comment by MaerF0x0** [comment]
@dannysheridan  if you know how, perhaps add one here for those of us who land here via search engines :)

**Comment by dsinghvi** [comment]
```yaml

Operator: 
  enum: 
    - name: LESS_THAN
      value: < 
```
