### ISSUE TITLE
Errors don't support examples

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#1193]
as a user, I'd expect this to work. it fails `fern check` with the error of "unexpected key _examples_"

once added, we should add an example to our Docs.

```
errors:
    DuplicateSsnError: 
        status-code: 400
        type: DuplicateSsn
        examples:
          - name: Example0 
            value: 
              error_type: BORROWER_ERROR
              error_code: DUPLICATE_SSN
              error_message: A borrower with that SSN already exists
```
