### ISSUE TITLE
[openapi importer] additionalProperties create unnecessary aliases

### ISSUE THREAD

**Issue by zachkirsch** [fern-api/fern#1201]
This OpenAPI map:
```yaml
"feature_flags": {
  "title": "Feature Flags",
  "type": "object",
  "additionalProperties": { "type": "boolean" }
}
```

creates this Fern Definition:
```yaml
feature_flags: optional<map<string, _InlinedType14>>
_InlinedType14: boolean
```
