### ISSUE TITLE
[openapi importer] allOf with one reference creates unnecessary alias

### ISSUE THREAD

**Issue by zachkirsch** [fern-api/fern#1202]
This OpenAPI yaml:

```yaml
"usage": {
  "allOf": [{ "$ref": "#/components/schemas/ProjectDataUsage" }]
},
```

creates this Fern yaml:

```yaml
usage: optional<_InlinedType20>

_InlinedType20:
  extends:
    - ProjectDataUsage
```
