### ISSUE TITLE
Docs for properties are not brought in

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#1211]
`docs` are not brought in for a property.

```
                      properties:
                        id:
                          type: string
                          description: The unique identifier for the applicant
```

<img width="732" alt="Screenshot 2023-01-24 at 12 09 09 AM" src="https://user-images.githubusercontent.com/83524670/214241106-5e5c33e3-e8ae-4061-aa84-8ef43f4f81ac.png">
