### ISSUE TITLE
Add a name property for the Request when query parameters, body, headers are present

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#1214]
If there are query-parameters, there should be a name: property that’s auto-populated

```
services:
  http:
    PropertiesService:
      auth: true
      base-path: /v1/properties
      endpoints:
        getAllProperties:
          path: /
          method: GET
          docs: Get all properties
          display-name: Retrieves all properties
          request:
            query-parameters:
              order-by: 
                type: optional<string>
                docs: | 
                  Order the results by a field. 
                  Optionally include asc or desc preceded by a colon (default is asc). 
                  Example: `?order-by=vendor:asc,created_at:desc`
```
