### ISSUE TITLE
Query parameters not present after importing

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#1223]
The following endpoint should have query parameters:

```
      endpoints:
        getApplicationLinks:
          path: /links
          method: GET
          docs: Lists an application's links.
          display-name: List Application Links
          response: commons../responses/Links.yaml
```

![Screenshot 2023-01-27 at 12 00 34 AM](https://user-images.githubusercontent.com/83524670/215036873-a494bdad-8e0b-4254-990a-33bad564ad5b.png)

https://tinyurl.com/example98df9u35y3
