### ISSUE TITLE
Lists of path-parameters are not imported

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#1255]
Fern doesn't support lists in path parameters. OpenAPI does.

Error: `Path parameter had non-primitive schema: {"items":{"type":"string"},"type":"array"}`

![Screenshot 2023-01-31 at 6 57 51 PM](https://user-images.githubusercontent.com/83524670/215934290-81d4372f-930d-473e-b033-b509beaa1cd9.png)

```
      - description: Code of the fulfillment center
        in: query
        name: fulfillment_center_code
        schema:
          items:
            maximum: 100
            type: string
          maximum: 100
          type: array
```
