### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#1273]
As a user, I'd like to add i18n to docs fields. You can either have a string or a map<string,string> where the first string is [ISO 639-2](http://www.loc.gov/standards/iso639-2/php/code_list.php) and the second string is the description.
```
  docs:
    eng: A simple Fern
    esp: Un simple Fern
    chi: 一个简单的Fern
```

Inspired by: https://github.com/OAI/OpenAPI-Specification/issues/274
