### ISSUE TITLE
OpenAPI importer ignores anyOf type

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#1338]
When an OpenAPI spec is used as the definition of an API, Fern ignores `anyOf` types and thus they're missing from the SDK.

For example, these two types do not get generated in the SDK (and they should):

```yaml
/events:
    get:
      operationId: getEvents
      parameters:
        - in: query
          name: id
          schema:
            anyOf:
              - type: string
                maxLength: 255
              - type: array
                items:
                  type: string
                  maxLength: 255
        - in: query
          name: status
          schema:
            anyOf:
              - type: string
                maxLength: 255
                enum:
                  - SCHEDULED
                  - QUEUED
                  - HOLD
                  - FAILED
                  - SUCCESSFUL
              - type: array
                items:
                  type: string
                  maxLength: 255
                  enum:
                    - SCHEDULED
                    - QUEUED
                    - HOLD
                    - FAILED
                    - SUCCESSFUL
```
