### ISSUE TITLE
Unions should support extends

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#1462]
Currently `unions` don't support extending other objects which forces users to create an additional type in fern and have all the subtypes extend it. 

Something like this should be possible 
```yaml
union:
  extends: commons.Thing
  base-properties:
    propertyA: string
  foo: Foo
  bar: string
```
