### ISSUE TITLE
Allow `key` field for non-primitive types in unions

### ISSUE THREAD

**Issue by zachkirsch** [fern-api/fern#1535]
Right now, we require the `key` field for primitives in unions:
```yaml
types:
  # json is either:
  # { "type": "x", "xValue": <some string> } or { "type": "y", "yValue": <some string> }
  Foo:
    union:
      x:
        type: string
        key: xValue
      y:
        type: string
        key: yValue
```

We should allow you to specify this `key` field if the `type` is an object
