### ISSUE TITLE
[spec] Add `status-code` to response

### ISSUE THREAD

**Issue by zachkirsch** [fern-api/fern#1583]
In the spec, you should be able to supply a 2xx status code, e.g.
```yaml
response:
  type: Foo
  status-code: 201
```
