### ISSUE TITLE
Make 'environment' key configurable in SDKs

### ISSUE THREAD

**Issue by zachkirsch** [fern-api/fern#1607]
By default we use the word `environment` when generating the SDK, but a user may want to configure the variable name. 

So instead of 
```typescript
const client = MyCompanyClient({
  environment: MyCompanyEnvironment.Staging,
});
```

it could be configured to 

```typescript
const client = MyCompanyClient({
  baseUrl: MyCompanyBaseUrl.Staging,
});
```

and we would implement by updating the spec. 

```
# api.yml
environments: 
  name: baseUrl
  urls: 
    Production: "url"
    Staging: "url"
```
