### ISSUE TITLE
Custom openapi input path

### ISSUE THREAD

**Issue by darr1s** [fern-api/fern#1626]
I am currently using fern on a turborepo monorepo.

```
- /apps/api/swagger-spec.json  (nest.js generates here)
- /packages/fern/fern/api/openapi/swagger-spec.json (init once created a copy here)
- /packages/fern/fern/generators.yml  (this does not support custom path)
- /packages/fern/fern.config.json
```

What is expected
```
default-group: local
groups:
  local:
    generators:
      - name: fernapi/fern-typescript-node-sdk
        version: 0.6.0
        output:
          location: local-file-system
          path: ../../generated/typescript
      - name: fernapi/fern-openapi
        version: 0.0.26
        **input:
          path: ../../../apps/api/swagger-spec.json**  (<-- support this parameters)
        output:
          location: local-file-system
          path: ../../generated/openapi
```

**Comment by zachkirsch** [comment]
Hey @darr1s, fern right now only supports reading from `fern/<api>/openpai/<your openapi spec>`. Can you try symlinking? `ln -s apps/api/swagger-spec.json packages/fern/fern/api/openapi/swagger-spec.json`

If that doesn't work, is it easy to add a step to your build process that copies the openapi spec from `apps/api/swagger-spec.json` to `packages/fern/fern/api/openapi/swagger-spec.json`?

**Comment by dsinghvi** [comment]
@darr1s https://stackoverflow.com/questions/51732236/generate-swagger-documentation-as-json-yaml-in-nestjs looks like you could also configure it to write it in both places

**Comment by dsinghvi** [comment]
@darr1s  https://github.com/fern-api/fern/pull/2214 we now support specifying the path in `generators.yml`. If you upgrade fern to the latest release candidate (by running `fern upgrade --rc`), you should be able to specify an input path in your `generators.yml`. 

```yaml
openapi: ../path/to/openapi # <--------- specify your path here
groups: 
 ...
```
