### ISSUE TITLE
Support code examples in spec

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#1786]
For people who want code snippets now or want to override code snippets, we should provide a way to do that in the spec. Proposal: 
```yaml

endpoints: 
  getUser: 
    path: /users/{userId}
    method: GET
    code-snippets: 
     - language: TypeScript
       sample: | 
         import { MyClient } from "my-api"; 
         const client = MyClient({
           apiKey: "apiKey"
         });
         const user = await client.users.getUser({
           "user-id"
         )};
```
