### ISSUE TITLE
Document the orm_mode flag for the FastAPI generator

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#1857]
We support `orm_mode` in the FastAPI generator but don't have it documented. 

for example:
```yaml
- name: fernapi/fern-fastapi-server
  ...
  config:
    orm_mode: true
```
