### ISSUE TITLE
Supporting multiple versions of the API Reference

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#1907]
There are companies that version each API with a `X-API-VERSION` header. In the docs they want to render the API Reference for each of these "versions". 

In this case a customer may want to specify multiple different OpenAPI specs or Fern Definitions and render each one. This means that the docs are no longer 1:1 with an API Definition and the existing configuration will need to change. 

## Proposal: docs.yml lives at the top-level

Assumptions: 
- A company may have multiple APIs but they only have one docs website. 
- A company wants to use one API definition for SDK generation. 
- A company wants to show multiple APIs in the docs. 

```yaml
fern/
  docs.yml
  api/
    openapi/
      primer-latest-openapi.yml
    generators.yml
  fern.config.json
```

```yaml
url: <org>.docs.buildwithfern.com
custom-domains: 
  - docs.<org>.com
navigation: 
  - section: Introduction
    pages: 
      - title: Getting Started
        page: getting-started.mdx
  - api: API Reference
    versions: 
       -  version: 2.2
          name: <api-one>
       -  version: 2.1
          name: <api-two>
```

**Comment by dsinghvi** [comment]
The current proposal doesn't support Staging and Production websites that well. 

Users want to publish a similar multiple urls (i.e. `<company>.docs.buildwithfern.com` and `<company-staging>.docs.buildwithfern.com`). 

 ## Solution: Support multiple URLs in `docs.yml` 
 
 ```
instances: 
  - url: <org>.docs.buildwithfern.com
    custom-domain: docs.<org>.com
  - url: <org>-staging.docs.buildwithfern.com
    custom-domain: docs.<org>.com
navigation: 
  - section: Introduction
    pages: 
      - title: Getting Started
        page: getting-started.mdx
  - api: API Reference
    versions: 
       -  version: 2.2
          openapi: ./openapi.yml
       -  version: 2.1
          definition: ../../definition
 ``` 

The CLI command `fern generate --docs <url>` could be used to generate docs for a particular url.
