### ISSUE TITLE
Check command should perform more verifications for doc builds

### ISSUE THREAD

**Issue by aevitas** [fern-api/fern#1916]
Currently, the `fern check` command only validates the structural integrity (i.e. is this valid YAML) of the documentation configuration file if present.

This means that valid YML, but invalid configuration, e.g. non-existent files, currently pass both `check` and `generate`:

```yml
  - section: Generators
    contents:
      - page: foo
        path: ./asdadsad/dsadsa
```

Which also gets published:

![image](https://github.com/fern-api/fern/assets/151426/866439e4-891f-4233-8062-df139292b3fc)

Obviously this file does not exist, and I'd expect an error either at `check` or `generate` time, but not at runtime.
