### ISSUE TITLE
Support first-class cookie auth

### ISSUE THREAD

**Issue by stephenkao** [fern-api/fern#1925]
Adding `auth: true` in a definitions file enables token-based auth, but it'd be great if there were support for cookie auth.  An idea proposed in [the Discord thread](https://discord.com/channels/988611740499574794/988611741476859916/1130898164233273365) would be to allow specifying a cookie-type auth and the cookie name to look for:

```yml
auth: 
  type: cookie
  name: My-Cookie-Name
```

Theoretically, this'd obviate the need to specify the token when we create the API client on the front end for first-party cookies (since they should be passed along to the back end automatically):

```ts
new ApiClient({
  environment: ...,
  token: ... // this is required when auth: true
});
```

The token approach is admittedly more flexible, but it'd be a nice convenience to have cookie auth as well!

**Comment by dannysheridan** [comment]
I'm working with an OpenAPI spec that has cookie auth as one of the auth schemes. Support in Fern would be great.

```
      security:
        - cookieAuth: []
        - basicAuth: []
        - {}
``` 

```
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
```
