### ISSUE TITLE
Simplify http config

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#196]
```
DayOfWeekService:
      auth: none
      endpoints:
        getCurrentDayOfWeek:
          method: GET
          path: /day-of-week
          response: DayOfWeek
```

Our opinion is that many devs will don't actually care about the `method` or `path` of the endpoint as long as they can declare inputs and outputs. 

Fern should support devs not specifying `method` or `path`. It can default `method` to `POST` and `path` to the endpoint id. This provides the flexibility to integrate existing APIs while allowing devs to iterate faster on their APIs by reducing config required.
