### ISSUE TITLE
Support `HMAC` auth scheme

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#1984]
Add a HMAC auth scheme to the fern definition like below
```yaml
auth: HmacAuthScheme
auth-schemes: 
  HmacAuthScheme: 
    scheme: hmac
    header: X-API-HMAC
    hash: sha256 # <-------- later can add support for other hash functions if needed
```

Each generator would then understand how to generate code for the HmacAuthScheme. For example, in TypeScript the generated code should look like and the hmac auth header would be computed inside of each endpoint. 

```typescript
const client.= MyCompany.Client({
  secretKey: "SECRET_KEY",
});
```
