### ISSUE TITLE
More clear examples on Fern docs of how to add examples.. lol

### ISSUE THREAD

**Issue by Tyler-O-Douglas** [fern-api/fern#1992]
Adding example values to display in the example request is complicated and it's hard to find in your docs how to do it right.

**Comment by dsinghvi** [comment]
Thanks for filing this issue @Tyler-O-Douglas, hear you that examples are complicated

**Comment by dannysheridan** [comment]
+1 as I'm trying to do this right now and referencing issues to figure out how...

**Comment by dannysheridan** [comment]
helpful reference:

```
  ShipTo:
    properties:
      street1: string
      street2: optional<string>
      city: string
      state: string
      postalCode: string
      country: Country
      isResidential: boolean
    examples:
      - name: WhiteHouse
        value:
          street1: 1600 Pennsylvania Avenue NW
          city: Washington DC
          state: Washington DC
          postalCode: "20500"
          country: US
          isResidential: false
```
