### ISSUE TITLE
Failed to convert schema 

### ISSUE THREAD

**Issue by suhailkakar** [fern-api/fern#2000]
Hello!

When I run `fren generate`, it gives the below error:

```
Failed to convert schema breadcrumbs=["new-asset-payload","storage","ipfs","NewAssetPayloadStorageIpfs","spec","NewAssetPayloadStorageIpfsNewAssetPayloadStorageIpfsSpec"] value={"type":"null"}
```

Here is the link of to the openapi spec: https://github.com/livepeer/studio/blob/master/packages/api/src/schema/api-schema.yaml

Not sure, if there is an issue in spec or Fren. Would appreciate any help!

**Comment by dsinghvi** [comment]
https://github.com/livepeer/studio/blob/d51438ae31d13980529b6c98dd5d19216e35fc24/packages/api/src/schema/api-schema.yaml#L1007 I believe this line is not being handled by our OpenAPI importer

**Comment by dsinghvi** [comment]
interesting are you not prefixing the schemas with `components/schemas` ?

**Comment by suhailkakar** [comment]
It is actually in this format: `#/components/schemas/stream/properties/name`

**Comment by dan-j** [comment]
Hey! I'm also running into this problem, but when using `oneOf`. Happy to create a new issue if you think it's not relevant to this.

fern version: 0.12.0

I have an OpenAPI 3.1.0 schema like:

```yaml
components:
  schemas:
    Thing:
      type: object
      properties:
        publishedAt:
          format: date-time
          readOnly: true
          description: >
            PublishedAt is the time at which the Thing was published.
          oneOf:
            - type: string
            - type: 'null'
      required:
        - publishedAt
```

We're currently using ogen for generating our server side code (although also keen to use fern for that if you support Go server-side generation in future), and ogen has a limitation on not supporting `type` as arrays, hence the weird `oneOf`. It would be good if we could support this for our TypeScript browser SDK.
