### ISSUE TITLE
Fern CLI shouldn't require login

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#2003]
Fern requires login to generate code, which prevents usage in large open source repos where there may be several contributors or in organizations that don't want to share information/rely on our servers. 

### Why did we require login? 

1. Identify verification: If you want to publish your SDK to a registry (e.g. npm.buildwithfern.com), mirror code to Github or generate a docs website then Fern needs to make sure that you are indeed the person that is allowed to publish to that location. 
2. Support: If a user runs into an error, we are easily able to reach out and help them troubleshoot. 

## Proposal: Don't require login when generating code locally

Fern supports an entirely local mode to generate code where we spin up the generator as a docker and output files to disk. There's no reason to require login for this mode. 

If you do `fern add <generator> --mode docker` or add the `mode: docker` field to your generator, then fern will run locally and not require login. 

```yaml
groups: 
  server: 
    - name: fernapi/fern-fastapi-server
       version: 0.3.8
       mode: docker # <-------------
       output: 
         location: local-file-system
         path: ../a/bc
```

Note that if the mode is docker but the output is npm or pypi, then the CLI will throw an error. 

With this command we will also deprecate `fern generate --local`
