### ISSUE TITLE
Unions don't prevent property naming conflicts

### ISSUE THREAD

**Issue by amckinney** [fern-api/fern#2061]
Right now, `fern` prevents types from having conflicts between their properties and any of their extended type's properties like so:

```yaml
# type.yml
types:
  Name:
    properties:
      name: string
  Type:
    extends: Name
    properties:
      name: boolean
```

```sh
$ fern check
[api]: type.yml -> types -> Type
       Object has multiple properties named "name":
         - Type -> name
         - Type -> (extends) Name -> name
```

However, the same is _not_ true for unions. The following schemas should fail `fern check` with a similar error:

```yaml
types:
 Type:
  properties:
   value: boolean
 Union:
  extends: Type
  union:
   conflict: string # Sent as 'value' in JSON.
```

```yaml
types:
 Type:
  properties:
   name: boolean
 TypeTwo:
  properties:
   name: string
 Union:
  extends: Type
  union:
   typeTwo: TypeTwo
```
