### ISSUE TITLE
Possible to use arbitrary OpenAPI Extensions?

### ISSUE THREAD

**Issue by Arkessler** [fern-api/fern#2089]
Hello, first of all, thank you very much for maintaining Fern, it's been a big help in getting our SDKs up and running.

I'm looking to set a couple OpenAPI Extensions on our endpoints. Our current workflow is that we're using Fern to generate an OpenAPI spec and SDKs, then importing the OpenAPI spec to the docs tool Readme. In order to customize how the docs are rendered, I'd like to be able to set the following two code extensions on every API endpoint we have

- Change the code samples (want to set them to show examples of using the SDK, rather than generic HTTP calls): https://docs.readme.com/main/docs/openapi-extensions#custom-code-samples
- Disable the Readme "Try It" button: https://docs.readme.com/main/docs/openapi-extensions#disable-the-api-explorer

I read the Fern doc about supporting OpenAPI Extensions: https://buildwithfern.com/docs/spec/extensions, but it confused me.

The phrase "Fern supports different OpenAPI extensions so that you can generate higher-quality SDKs. If there’s an extension you want that doesn’t already exist, file an [issue](https://github.com/fern-api/fern/issues/new)." seemed to indicate that Fern only supports a limited set of OpenAPI Extensions, but I'm unsure whether that's true. If that's the case, I would have expected a table in the doc with all supported extensions.

Is it possible to set arbitrary OpenAPI extensions by adding them to somewhere in the Fern spec? That would be ideal, as I expect to encounter other extensions I need to make over time. Or does each potential extension need to be added to Fern as a new feature?

**Comment by dsinghvi** [comment]
@Arkessler thanks for the issue -- 

The docs page that you [read](https://buildwithfern.com/docs/spec/extensions) is for people who _start_ with OpenAPI instead of the Fern Definition. In your case, it sounds like you start with the Fern Definition but you want to be able to generate extensions in the OpenAPI spec that you can use when importing into README. 

Couple solutions: 
1. You can try using Fern for documentation instead, we have a hosted docs offering that we are about to launch more broadly. Example documentation: https://docs.vellum.ai/. We are working on having auto-generated SDK examples so that you don't have to manually write those. 
2. [Requires development] We have thought about adding `extensions` as a key in the fern definition. Every type, property, endpoint would support this field and every fern generator would be able to reach in and use the arbitrary extensions. So in your case the OpenAPI generator would have have to be amended to read `extensions` and then output them in the OpenAPI spec. 
```
types: 
  MyThing: 
    extensions:  # <-------------- arbitrary metadata storage
      myKey: myVal 
    properties: 
      a: 
        type: string

service: 
  endpoints: 
    doThing: 
        extensions:  # <-------------- arbitrary metadata storage
          myReadmeCodeSnippet: 
             python:  | 
                import requests
                
                requests.put()
               
      
```


Since we are really getting in the weeds, it might be useful to talk through this on a zoom. Here's my calendar if useful: https://calendly.com/deep-singhvi/30min?month=2023-08.
