### ISSUE TITLE
Validate that all undiscrimianted unions have types defined

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#2115]
If I have an undiscriminatd union where a type isn't defined, `fern check` still passes. I'd expect an error message along the lines of "`Bar` is undefined."
```  
MyType: 
    discriminated: false
    union:
      - Foo
      - Bar

Foo: string
```
