### ISSUE TITLE
Fern CLI + code generation should support pagination

### ISSUE THREAD

**Issue by zachkirsch** [fern-api/fern#22]
The generated SDK should make it very easy to 1/ iterate over all pages, 2/ ask simple questions like `.is_next_page_available()`. In order to do this the Fern Definition must understand what the pagination scheme is.

**Comment by zachkirsch** [comment]
```yaml
types:
  GetAllUsersResponse:
    properties:
      users: list<User>
      nextPage: optional<string>

...

getAllUsers:
  query-parameters:
    page: string
  response: GetAllUsersResponse
  pagination:
    pageQueryParam: page
    nextPageResponseProperty: nextPage
```
