### ISSUE TITLE
IR migrator shortcomings

### ISSUE THREAD

**Issue by amckinney** [fern-api/fern#2241]
## Problem

The introduction of the IRv28 -> IRv27 migration revealed a shortcoming with the IR migration process. That migration in particular transforms all boolean literals into boolean properties, but this has unintended consequences on a small subset of in-lined request type declarations.

For example, consider the following in-lined request definition:

```yaml
service:
  auth: false
  base-path: /
  endpoints:
    get:
      path: ""
      method: POST
      request:
        name: GetRequest
        headers:
          literalEndpointHeader: literal<"endpoint header">
          falseEndpointHeader: literal<false>
```

When the IR is originally created, Fern recognizes that the in-lined request name information isn't really necessary because all of the properties associated with it are literals. So `fern` actually _drops_ the `sdkRequest` information from the IR entirely [here](https://github.com/fern-api/fern/blob/e84caf19642e970422c3e8cdafb1cc4b9fa866c4/packages/cli/generation/ir-generator/src/converters/services/convertHttpSdkRequest.ts#L73).

Given the definition above, if a user runs an old generator that doesn't support boolean literals, they will encounter an error because the generator won't have access to the in-lined request name (via the `sdkRequest` field) even though it needs it to actually leverage the `boolean` property. To be clear, this will only happen when _all_ of the fields associated with an in-lined request are literals, which is uncommon.

## Next steps

This revealed a shortcoming of the IR migration process - there's a strong assumption that the IR will always have _more_ information than what is required in previous versions, but this edge case is a counterexample to that claim. A quick fix would be to simply include the `sdkRequest` regardless of whether or not it can be pruned in the IR, but that goes against the IR's philosophy that the IR should inform the generator as much as possible (i.e. omitting the value tells the generator, "You better not require the user to specify a request - they're all literals!").

We're guaranteed to encounter other similar problems like this, so we'll need to think about this philosophy in general to see what the best path forward is here
