### ISSUE TITLE
[Bug] Referenced examples in union definitions do not work

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#2244]
**Describe the bug**
Referencing other examples in a union definition does not work. For example, in the following yaml definition when i run `fern check` this will fail with `Expected example to be an object`. 

```yaml
Shape: 
  union: 
     triangle: Triangle
     circle: Circle
   examples: 
     - name: Default
        value: $.Triangle.Default # <------------- Doesn't pass fern check
 
 Triangle: 
    properties: 
       a: int
       b: int
       c: int
     examples: 
        - name: Default
           value: 
              a: 2
              b: 3
              c: 4 
```

**Describe potential solutions**

Fern throws this error because the `fern check` rule for examples is looking for a discriminant property in the example and it does not see one. `fern check` should be updated to not expect a discriminant property when there is a direct reference to an example inside of a union.
