### ISSUE TITLE
Support regex + length based validation on string fields

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#2246]
**Is your feature request related to a problem? Please describe.**
Fern should support the ability to add validation to string fields 
```
types: 
  Address: 
    properties: 
      street: string
      zip: 
        type: string
        validations: 
          - message: "Zip code must be 5 digits"
             regex: ^\d{5}(?:[-\s]\d{4})?$
```

If the user's code does not match the regex, Fern will handle throwing a validation error on the server side. 

**Additional context**
It's also possible to render the validations as useful information in the docs.
