### ISSUE TITLE
[Feature] Docs generation from OpenAPI should respect `tag` order

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#2266]
**Is your feature request related to a problem? Please describe.**
There should be a way to control the navigation order of different endpoint groups when generating API Reference from OpenAPI. 

**Describe the solution you'd like**
```
tags: 
  - name: User
  - name: Project
  - name: Admin
```
should result in the API Reference ordering endpoints with users first, then projects, then admin.
