### ISSUE TITLE
[Bug] `fern check` does not check overlapping URL paths in the Documentation

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#2300]
**Describe the bug**
If there are two paths that overlap (i.e. two sections with the same name) then the docs will 500 because they dont know which page to render. `fern check` should validate against this and make sure that 

**To Reproduce**
Example of a `docs.yml` that causes this: 

```
navigation: 
  - section: API Reference
    layout: ...
 - section: API Reference
    layout: ...
```
**Expected behavior**
`fern check` should return an error message: 

```bash
> docs.yml -> navigation -> section -> 0 
Two different pages have URL conflicts, please change the section name or override using the slug property. 
```
