### ISSUE TITLE
[Bug] fern fails to parse nested map `map<string, map<string, int>>`

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#2316]
**Describe the bug**
When there is a type with a nested map, `map<string, map<string, Baz>>`, fern fails to parse this and fails with the errors

```bash
[api]: __package__.yml -> types -> SingleUserResourceResponse -> properties -> provider -> type
       Type string, map<string is not defined.
[api]: __package__.yml -> types -> SingleUserResourceResponse -> properties -> provider -> type
       Type Baz> is not defined.
```

**To Reproduce**
Run `fern check` on the following Fern definition

```
# baz.yml
types: 
    MyType:
      properties:
        bar:
          type: map<string, map<string, baz>>
```

**Expected behavior**
Fern should parse the nested map appropriately.
