### ISSUE TITLE
[Bug] Support mutualTLS security scheme 

### ISSUE THREAD

**Issue by fledman** [fern-api/fern#2321]
**Describe the bug**
fern python fails to validate + generate an openapi spec that uses a [`MutualTls`](https://www.cloudflare.com/learning/access-management/what-is-mutual-tls/) security scheme

**To Reproduce**

1. init firm with an openapi schema that includes a Security Scheme with `type: mutualTLS`
2. add the `fern-python-sdk` generator
3. run `fern check` or `fern generate`

**Expected behavior**
Code generation succeeds. Ideally with support for MTLS, but in the worst case, ignoring the scheme it doesn't understand.

**Actual behavior**
```
[api]: Failed to convert security scheme {"type":"mutualTLS","description":"Certificate Name"}
```

**Desktop (please complete the following information):**

- OS: macOS Ventura 13.4
- Browser: Chrome 

**Additional context**
```yaml
security:
  - MutualTls: []
```
```yaml
components:
  securitySchemes:
    MutualTls:
      type: mutualTLS
      description: Certificate Name
```
