### ISSUE TITLE
Document how to override basic auth field names

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#2335]
Add an example of overriding the username and password field names for basic auth.

https://github.com/usewalletkit/fern/pull/4/files

```yaml
name: api
display-name: WalletKit
error-discrimination:
  strategy: status-code
auth: BasicAuthScheme
auth-schemes:
  BasicAuthScheme:
    scheme: basic
    username:
      name: projectID
    password:
      name: apiKey
default-environment: testnet
environments:
  testnet: https://testnet.usewalletkit.com
  mainnet: https://mainnet.usewalletkit.com
```
