### ISSUE TITLE
[Documentation] How to add `docs` to query parameters, path parameters, and headers

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#2339]
We should specify the syntax for adding `docs` to query parameters, endpoint headers, and path parameters

For example:
```
query-parameters:
  foo:
    docs: "i'm a docs!"
    type: string
```
