### ISSUE TITLE
[Documentation] How to add audiences to a type or property

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#2341]
### What can be improved

```
MyType: 
    properties:
      message: string 
    audiences: #<---
      - internal
```

```
 MyType: 
    properties:
      message: string 
      number: 
        type: double
        audiences:  #<---
          - internal
```
