### ISSUE TITLE
Nesting API reference within a section will build but the API reference site doesn't work properly

### ISSUE THREAD

**Issue by davidkonigsberg** [fern-api/fern#2378]
**Describe the bug**
When I attempt to nest the API Reference within a section, the site doesn't work properly.

**To Reproduce**

When I create an docs.yml nav section like this, it creates a site where the api docs page doesn't work quite right.
```yaml
instances:
  - url: XXXXXXXXXXXXX
title: Sayari | Docs
navigation:
  - section: Documentation
    contents:
      - page: Getting Started
        path: ./docs/pages/getting_started.mdx
      - page: Key Concepts
        path: ./docs/pages/key_concepts.mdx
      - page: SDKs
        path: ./docs/pages/sdks.mdx
  - section: API Usage
    contents:
      - page: Introduction
        path: ./docs/pages/introduction.mdx
      - page: Objects
        path: ./docs/pages/objects.md
      - api: API Reference
  - section: Use Cases
    contents:
      - page: Investigations
        path: ./docs/pages/use_case/investigations.mdx
      - page: Screening
        path: ./docs/pages/use_case/screening.mdx
```

tabbing out the `- api` to move it out from the section fixed it.

**Expected behavior**
Ideally I would like to be able to nest the API reference within a section just as I would any other page/set of pages.
If that isn't possible, the docs site should fail to generate.

**Screenshots**
Nothing much to show, the site renders but it is the interactions that do not work properly.

**Desktop (please complete the following information):**

- OS: Mac
- Browser: Safari
- Version: latest
