### ISSUE TITLE
[Feature] `x-fern-ignore` OpenAPI extension works on schemas

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#2417]
### Problem description

`x-fern-ignore` should work on schemas and the converter should ignore bringing those schemas in

### Why would it be useful?

This would be useful if folks want to exclude certain redundant or internal schemas from Fern. 

### Describe the solution (optional)

```
components: 
  schemas: 
     MyType: 
        x-fern-ignore: true # <----- ignore
        proeprties: 
          ...
```
