### ISSUE TITLE
[Feature] `x-fern-sdk-group-name` is supported on OAI schemas

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#2418]
### Describe the bug
Fern has the ability to scope schemas into categories, unlike OpenAPI. This makes the SDK easier to read bc types are grouped by concept instead of being in a single top level folder. 

### Solution
```yaml
components: 
  schemas: 
    MyType: 
      x-fern-sdk-group-name: bla
      properties: 
         ...
```

will produce 

```yaml
# bla.yml

types: 
  MyType: 
    ...
```
