### ISSUE TITLE
[Feature] Allow availability on union variants + enums + errors

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#2423]
### Describe the bug
Unions and enum values should have an associated availability and the docs + SDKs should make it clear to a developer if they are relying on something that is beta or deprecated. 

### Expected behavior
```yaml
MyEnum: 
  - value: boo
    availability: deprecated # introduce availability here
```

```yaml
MyUnion: 
  bar: 
    availability: deprecated  # introduce availability here
    type: Bar
```

```yaml
errors: 
  MyError: 
    availability: deprecated # introduce availability here
```

**Note: ** The IR should also be updated to contain this availability
