### ISSUE TITLE
[Bug] Long function names are truncated within python

### ISSUE THREAD

**Issue by armandobelardo** [fern-api/fern#2431]
### Describe the bug
_(I believe this is the issue, would need some time to reproduce it or look into the code, but haven't had a chance. There are technically no limits within Python itself, which is the confusing part, but once I modified the operationIds things worked.)_

Ambiguous error occurs when generating Fern spec from OpenAPI spec, method names are claimed to conflict, and then [consulting the Fern documentation](https://docs.buildwithfern.com/api-definition/openapi/extensions#sdk-method-names), it appears as though the method names should not conflict as the operationIds throughout the spec are unique (see snippet below)
```
The OpenAPI Spec has conflicting sdk method names. See POST <ENDPOINT PATH, NOT METHOD NAME>
```

My assumption is that this happens as somewhere the method name is truncated, however I have not been able to validate that.

### To reproduce
Run fern generate with an OpenAPI spec including longer operationIds, this was the content flagged within mine:
```
  /v1/text-to-speech/{voice_id}:
    post:
      tags:
        - text-to-speech
      operationId: Text_to_speech_v1_text_to_speech__voice_id__post
  /v1/text-to-speech/{voice_id}/stream:
    post:
      tags:
        - text-to-speech
      operationId: Text_to_speech_v1_text_to_speech__voice_id__stream_post

```

### Expected behavior
The Fern generation completes successfully, with painfully long function names (probably with a warning, explaining how method names are generated and that these method names will be long), or a well defined error is presented to the user ("SDK method names detected of length longer than X: {METHOD WITH LONG NAME LIST}. The Fern OpenAPI extension uses the tag and operationId fields to generate the SDK method names, please update your OpenAPI definition to meet these requirements.")

### Links
[If applicable, add screenshots to help explain your problem.](https://discord.com/channels/988611740499574794/1180144536127819886)

### Versions
- Desktop OS: [e.g. macOS, Windows, Linux]   macOS
- Fern Version: [e.g. 0.15.5; found in `fern.config.json`] 0.15.10, python-sdk v 0.6.2
