### ISSUE TITLE
[Feature] Identify literal examples with ExampleLiteral

### ISSUE THREAD

**Issue by amckinney** [fern-api/fern#2438]
### Problem description

The example IR currently obfuscates whether or not a parameter is a literal value because all example values are just literal values.

### Why would it be useful?

This will make it easier to author generators that interact with examples (i.e. snippet generation).

### Describe the solution

We should modify the `ExampleContainer` type so that it mirrors the primary `Container` type, such that it includes an `ExampleLiteral` like so:

```yaml
ExampleContainer:
  union:
    list:
      type: list<ExampleTypeReference>
      key: list
    set:
      type: list<ExampleTypeReference>
      key: set
    optional:
      type: optional<ExampleTypeReference>
      key: optional
    map:
      type: list<ExampleKeyValuePair>
      key: map
    literal:
      type: list<ExampleLiteral>
      key: literal

ExampleLiteral:
  properties:
    # Although all literals are just ExamplePrimitive types today, this might not always be true.
    value: ExampleTypeReference
```

**Comment by dsinghvi** [comment]
i think we should just assume that literals are booleans/strings for now and we can always add to the union: 

```
ExampleLiteral: 
  union: 
    string: string
    boolean: boolean
```
