### ISSUE TITLE
[Feature] Add support for example file upload and bytes requests

### ISSUE THREAD

**Issue by amckinney** [fern-api/fern#2439]
### Problem description

Re: https://github.com/fern-api/fern-python/pull/417#discussion_r1414578880

There's a gap between the `HttpRequestBody` and the `ExampleRequestBody`, as shown below:

```yaml
  HttpRequestBody:
    union:
      inlinedRequestBody: InlinedRequestBody
      reference: HttpRequestBodyReference
      fileUpload: FileUploadRequest
      bytes: BytesRequest

  ExampleRequestBody:
    union:
      inlinedRequestBody: ExampleInlinedRequestBody
      reference: types.ExampleTypeReference
```

### Why would it be useful?

This will let users specify examples for _all_ their endpoints, not just the more traditional ones.

### Describe the solution

Update the IR and include the changes required in the compiler.
