### ISSUE TITLE
[Fern's Documentation] Support for Page Meta Descriptions

### ISSUE THREAD

**Issue by noanflaherty** [fern-api/fern#2443]
### Problem description

Fern-generated documentation pages do have meta descriptions, nor is there a way to author them. This results in no preview-text showing up in google searches, and poor SEO ratings.

### Why would it be useful?

You can learn more about meta descriptions and their usefulness in the world of SEO [here](https://www.semrush.com/blog/meta-description/). The consequence of not having them is that our global `vellum` domain is penalized by search engines and even non-doc-related pages (e.g. our marketing website) show up lower in searches.

### Describe the solution (optional)

We'd like the ability to author meta descriptions for each page. V2 of this might be using AI to auto-generate a draft of the meta description for me.

### Additional context

N/A

**Comment by dsinghvi** [comment]
@noanflaherty the way we would do this is update the markdown files to have a header: 

```mdx
---
title: Here's my title
meta: Here's a meta tag for SEO 
---
 ...content
 ```
 
 Would that format work well for you?

**Comment by noanflaherty** [comment]
I could see it either living there, or in the navigation definition. For example:

```
navigation:
  - tab: help
    layout:
      - section: Welcome
        contents:
          - page: Welcome to Vellum
            path: ./docs/content/help/welcome/intro.mdx
            slug: welcome
            meta: Here's a meta tag for SEO 
```

With your proposal, I'm left wondering as to what takes precedence – the `title` defined in this header, or the value of `page` in the navigation config.
