### ISSUE TITLE
[Bug] Idempotency headers must be optional; support in example IR

### ISSUE THREAD

**Issue by amckinney** [fern-api/fern#2454]
### Describe the bug

The recent addition of [idempotency headers](https://github.com/fern-api/fern/pull/2318) is not reflected in the example IR. This means that snippets will not contain all the parameters required to invoke an endpoint if there are any required idempotency headers defined.

However, this revealed another issue - idempotency headers should _always_ be marked as optional. Otherwise, the headers should just be treated ordinary headers that can either be defined globally or on the endpoint-level.

### To reproduce

```yaml
# api.yml
name: idempotency-headers
auth: bearer
idempotency-headers:
  Idempotency-Key: string
  Idempotency-Expiration: integer
```

```yaml
# service.yml
service:
  auth: true
  base-path: /payment
  endpoints:
    create:
      method: POST
      path: ""
      idempotent: true
      request:
        name: CreatePaymentRequest
        body:
          properties:
            amount: integer
      response: uuid
  examples:
    - request:
        amount: 42
      # The idempotency headers are consolidated here in this demonstration, but we
      # might actually want to use a separate idempotency-headers key for them.
      headers:
        Idempotency-Key: key
        Idempotency-Expiration: 60
```

### Expected behavior

`fern` should fail when any of the `idempotency-headers` are set to non-optional types. Snippets should be produced with all the parameters required to issue the call.
