### ISSUE TITLE
Unable to create examples for endpoints with multiple query parameters

### ISSUE THREAD

**Issue by davidkonigsberg** [fern-api/fern#2474]
### Describe the bug
When I try to create an example with multiple values for a query parameter, I get an error.

### To reproduce

Try to create an endpoint example like this:
```yaml
examples:
  - query-parameters:
      entities:
        - abcd
        - efgh
```

Observe error `Expected example to be a string. Example is: ["abcd","efgh"]`

### Expected behavior
If you can build a spec that accepts multiple values for a query parameter, you should be able to create an example use case with multiple values for a query parameter.

### Screenshots
N/A

### Versions
- Desktop OS: macOS
- Fern Version: 0.16.3
