### ISSUE TITLE
[Feature] Check that APIs referenced in `docs.yml` exist

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#2515]
### Problem description

`fern check` does not validate that each API named in your navigation exists

```yaml
navigation:
  - tab: api-reference
    layout:
      - api: Foo
        api-name: foo
      - api: Bar
        api-name: bar
```

### Why would it be useful?

Prevents frustration when trying to build docs with a typo or incorrect API name.
