### ISSUE TITLE
[Bug] Don't hyphenate certain words in doc urls

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#2537]
### Describe the bug
SDKs is hyphenated in the following examples:
https://docs.mercoa.com/sd-ks/sd-ks/java
https://docs.buildwithfern.com/generate-sd-ks

### To reproduce

```yaml docs.yml
- section: SDKs
    contents:
      - page: Javascript (Node/Browser)
        path: ./docs/sdks/javascript.mdx
```
