### ISSUE TITLE
[Feature] Describe Request + Response Pairs in OpenAPI

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#2539]
### Problem description

As a user, I want to 

### Why would it be useful?

In the Fern Definition, I can associate a request & response as shown below. I'd like to do the same in OpenAPI using a Fern-specific extension.

```yml movie.yml
service:
  base-path: /movies
  endpoints:
    create:
      method: POST
      path: /create-movie
      request: CreateMovieRequest
      response: MovieId
      examples:
        - name: Shawshank Example
          request:
            title: The Shawshank Redemption
            rating: 9.3
          response:
            body: tt0111161
        - name: Shindler Example
          request:
            title: Shindler's List
            rating: 9.0
          response:
            body: tt0108052
```

### Describe the solution (optional)

🧠 

### Additional context

Discussion here: https://github.com/OAI/OpenAPI-Specification/issues/1742
