### ISSUE TITLE
[Feature] Object Oriented SDKs

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#2544]
### Problem description

Often times, SDK resources are interconnected and it is more natural to propagate these relationships directly into the SDK. See the snippet below, which uses the Github API as an example

```python
const user = client.user.get("user-id..."); 
const repositories = user.get_repos(); 
```

In the example above, you can call `get_repos` on the user response and the method handles grabbing the user id from the response + calling the filter repository endpoint. 

### Why would it be useful?

For interconnected/graph-like APIs this is really intuitive for users and reduces boilerplate. 

### Describe the solution (optional)

The solution here is to introduce a new primitive into fern, called "methods". Every type defined in the API can have methods, which make calls to API endpoints. For the users example above, this is what the Fern Definition would look like: 
```yaml
imports: 
  repos: repos.yml

types: 
  User: 
    methods: # <---------------  new methods key
      get_repos: # <------------  name of method
        endpoint: repos.list # <--- the endpoint to proxy to 
        parameters: 
          user_id: $.id  # <-------- any parameters to pass in from the type itself
    properties: 
      id: 
        type: string
        docs: The ID of the user. 
```

For users coming from OpenAPI, we would support a `x-fern-methods` extension directly on the schema. 

```yaml
components: 
  schemas: 
    User: 
      x-fern-methods: 
        get_repos: 
           path: /users
           method: POST
           parameters: 
             user_id: $.id
      properties: 
        id:
          type: string 
```
