### ISSUE TITLE
[Fern's Documentation] Document `push` to branch mode for GitHub repo

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#2547]
### What can be improved

Introduce a new mode: push, to push the generated code to a github repository. If branch is not specified, the default branch will be used.

```yaml generators.yml
github: 
  mode: push
  repository: customer/customer-python
  branch: feature-abc # <---- the PR will be targeted from this branch  
```

### Link a PR (optional)

https://github.com/fern-api/fern/pull/2546
