### ISSUE TITLE
[Fern's Documentation] How to add SDK code snippets to your Fern Docs

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#2558]
### What can be improved

A user needs to provide a `package-name` in generators.yml and then include this name in `docs.yml` under the API reference section.

```yaml generators.yml
production:
    generators:
      - name: fernapi/fern-python-sdk
        version: 0.6.5
        output:
          location: pypi
          package-name: vellum-ai # <----- this field needs to be added
          token: ${PYPI_TOKEN}
        github:
          repository: vellum-ai/vellum-client-python
```

```yml docs.yml
navigation:
  - api: API Reference
    api-name: api
    snippets:
      python: vellum-ai  
```
