### ISSUE TITLE
[Feature] Configure the font size

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#2571]
### Problem description

As a user, I want to control the font size within my docs.

### Why would it be useful?

Visual presentation and to ensure consistency with my marketing websit.

### Describe the solution (optional)

```yaml
typography:
  headingsFont:
    path: ./fonts/Inter-Bold.woff2
    size: 24 # <---- proposed configuration
  bodyFont:
    path: ./fonts/Inter-Regular.woff2
  codeFont: 
    path:  ./fonts/Roboto-Mono-Regular.woff2
```

### Additional context

In addition to size, here are other attributes we could make configurable:

![Screenshot 2024-01-08 at 12 31](https://github.com/fern-api/fern/assets/83524670/a0297efa-bb88-4950-8cc2-1c4bfa0af490)
