### ISSUE TITLE
`fern check` should exit 1 on parsing failure to cause CI to fail

### ISSUE THREAD

**Issue by mjpierfinance** [fern-api/fern#2597]
### Describe the bug
When `fern check` encounters `Failed to parse` errors it should exit 1 so CI fails instead of passing.

### To reproduce
1. Create any `yml` file with invalid indentation
2. Run `fern check` inside of github actions
3. Review the CI and it will pass instead of fail

Using the starter this would pass but should fail:
```
types:
  MovieId: string

  Movie:
    properties:
      id: MovieId
      title: string
      rating:
        type: double
        docs: The rating scale is one to five stars
      invalid:
      invalid2:

  CreateMovieRequest:
    properties:
      title: string
      rating: double

service:
  auth: false
  base-path: /movies
  endpoints:
    createMovie:
      docs: Add a movie to the database
      method: POST
      path: /create-movie
      request: CreateMovieRequest
      response: MovieId

    getMovie:
      method: GET
      path: /{movieId}
      path-parameters:
        movieId: MovieId
      response: Movie
      errors:
        - MovieDoesNotExistError

errors:
  MovieDoesNotExistError:
    status-code: 404
    type: MovieId
```

### Expected behavior
The CI is expected to fail.

### Screenshots
![image](https://github.com/fern-api/fern/assets/147445167/9ce442ab-4b3d-4f7c-9d5a-baf5b381a110)

### Version
0.16.25
