### ISSUE TITLE
[Feature] Analytics for tracking viewer events

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#2614]
### Problem description

As a user, I can integrate with an analytics platform to track viewer events.

### Why would it be useful?

If I use google analytics, posthog, segment, pendo, plausible, logrocket, google tag manager, etc. I want to be able to capture events from my users on Fern Docs.

### Describe the solution (optional)

In `docs.yml`:
```yaml
...
analytics:
  posthog:
    apiKey: <key>
  pendo:
    apiKey: <key>
...
```
