### ISSUE TITLE
[Feature] Introduce fern.yml

### ISSUE THREAD

**Issue by amckinney** [fern-api/fern#2623]
## Overview

This issue tracks the introduction of a simpler `fern.yml` configuration file which is responsible for configuring the user's API definition, documentation, and generators.

## Background

`fern` configuration is currently split across a few different files and the `fern/` directory ends up being initially difficult to grok. 

For example, a typical OpenAPI user sees something like the following:

```sh
fern/
├── definition
│   └── api.yml
├── docs.yml
├── fern.config.json
├── generators.yml
└── openapi
    ├── acme.yml     # For a hypothetical Acme organization.
    └── common.yml
```

To be clear, the user needs to configure their `fern` version in `fern.config.json`, specify the generators in `generators.yml`, and manage their docuemntation in `docs.yml`.

## Solution

All these configuration values can be consolidated in a single `fern.yml` file with a structure similar to the following:

```yaml
# fern.yml
openapi:
  acme: openapi/acme.yml
  common: openapi/common.yml

artifacts:
  node-sdk: 
    sources:
      - acme
      - common
    output: 
      location: ...
  python-sdk: 
    sources: 
      - acme
    output: 
      location: ....

docs:
  urls:
    - https://acme.docs.buildwithfern.com/
```

With this, the user would have a far simpler directory structure like so:

```sh
fern/
├── definition
│   └── api.yml
├── fern.yml
└── openapi
    ├── acme.yml
    └── common.yml
```

This would also simplify the `fern generate` experience so that the users can simply run the following (where the argument matches the name of the configured `artifact`):

```sh
$ fern generate node-sdk
$ fern generate python-sdk
```
