### ISSUE TITLE
[Fern's Documentation] How to add nested sections in Fern Docs

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#2664]
### What can be improved

As an author of docs, I want to know how I can add a section header with a toggle and pages within it. I may want to nest a section within another section. 

### Example in production 

```yaml
navigation:
  - tab: guides
    layout:
      - section: Learn
        contents: 
          - section: Key Concepts
            contents: 
              - page: Embeddings
                path: ./docs/pages/embeddings.mdx
              - page: Prompt Engineering
                path: ./docs/pages/prompts.mdx
              - page: Tokens
                path: ./docs/pages/tokens.mdx
          - section: Generation
            contents: 
              - page: Command Nightly
                path: ./docs/pages/command.mdx
              - page: Likelihood
                path: ./docs/pages/likelihood.mdx
              - page: Number of generations
                path: ./docs/pages/generation.mdx
              - page: Temperature
                path: ./docs/pages/temperature.mdx
```
![nesting](https://github.com/fern-api/fern/assets/83524670/6dc55e8c-0b7b-4ef0-ab13-2b48a5dbf424)
