### ISSUE TITLE
[Bug] Circular references involving inheritance fail

### ISSUE THREAD

**Issue by armandobelardo** [fern-api/fern#2700]
**Describe the bug**
Circular references that include inheritance fail, example pared back model below

**Fern Definition To Reproduce**
```
types:
  FieldValue2:
    properties:
      parent: FieldValue
  FieldValue:
    properties:
      parent: AnotherContainerValue
  ContainerValue:
    extends: FieldValue2
    properties:
      child: FieldValue
  AnotherContainerValue:
    discriminated: false
    union:
      - ContainerValue
      - FieldValue
```

**Expected behavior**
I'd expect this to run successfully, however this leads to some errors when instantiating the client:
```
```

**Versions**
 - Generator: leveraging seed, so it's based on the latest (0.7.5 at time of writing)
