### ISSUE TITLE
[Bug] Don't generate literal query parameters and literal request body parameters

### ISSUE THREAD

**Issue by amckinney** [fern-api/fern#2704]
**Describe the bug**

Similar to https://github.com/fern-api/fern-python/pull/439, but for all other relevant parameters.

**Fern Definition To Reproduce**

```yaml
service:
  auth: false
  base-path: /only-literal-query-parameters
  endpoints:
    get:
      path: ""
      method: GET
      request:
        name: OnlyLiteralQueryParametersRequest
        query-parameters:
          literalQueryParameter: literal<"query parameter">
          falseQueryParameter: literal<false>
      examples:
        - query-parameters:
            literalQueryParameter: query parameter
            falseQueryParameter: false
```

**Expected behavior**

The endpoint snippet should _not_ specify the literal values in the invocation.

**Additional context**

Ideally we will have added the `ExampleLiteral` type to the IR to make this change simpler (re: https://github.com/fern-api/fern/issues/2438)
