### ISSUE TITLE
[Feature] Adding docs makes optional named parameters required

### ISSUE THREAD

**Issue by adamsuskin** [fern-api/fern#2708]
When we have a field like so:
```
MyObject:
  properties:
    opt_str: optional<string>
```
This is what is generated:
```
opt_str: typing.Optional[str]
```

Once we add docs, like so:
```
MyObject:
  properties:
    opt_str:
      docs: "An optional string"
      type: optional<string>
```
This is what is generated:
```
opt_str: typing.Optional[str] = pydantic.Field(
        description=("An optional string")
    )
```
This means if I try to make a class of `MyObject`, it now requires the `opt_str` named parameter whereas before it did not.

I think the generated code to shoot for should be:
```
opt_str: typing.Optional[str] = pydantic.Field(
        None, description=("An optional string")
    )
```
where`None` is used as the default value for optional types, and `...` is used as the default value for required types.
