### ISSUE TITLE
[Bug] Optional file does not generate optional params for python client SDK

### ISSUE THREAD

**Issue by mscolnick** [fern-api/fern#2709]
```yaml
    createThing:
      method: POST
      path: /thing
      request:
        name: CreateThing
        body:
          properties:
            thingId: ApplicationId
            file: optional<file>
```

will generate the following:

```python
    def create_thing(
        self, *, thing_id: ThingId, file: typing.IO
    ) -> Thing:
        _response = httpx.request(
            "POST",
            urllib.parse.urljoin(f"{self._environment}/", "api/v1/thing"),
            data=jsonable_encoder({"thingId": thing_id}),
            files={"file": file},
            headers=remove_none_from_headers(
                {"Authorization": f"Bearer {self._token}" if self._token is not None else None}
            ),
            timeout=60,
        )
        if 200 <= _response.status_code < 300:
            return pydantic.parse_obj_as(Thing, _response.json())  # type: ignore
        try:
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)
```

but this does not allow `file` to be optional and tries to `.read()` it in the `request` method
