### ISSUE TITLE
Generator deletes everything in the output path

### ISSUE THREAD

**Issue by Swimburger** [fern-api/fern#2729]
## Describe the Bug
We store our spec at the root of the repo, so we want to use this configuration for generators.yml.

```yml
default-group: local
groups:
  local:
    generators:
      - name: fernapi/fern-openapi
        version: 0.0.28
        config:
          format: yaml
        output:
          location: local-file-system
          path: ..
```

Or

```yml
          path: ../openapi.yml
```

Issues:
- Specifying the path as a file name, still creates a directory.
- Specifying the path to `..` deletes everything from `..` and creates the OpenAPI file. We'd like it not to delete existing files.

### CLI Version
0.15.0-rc63

### Generator Version
```yml
      - name: fernapi/fern-openapi
        version: 0.0.28
```
