### ISSUE TITLE
[Bug] Unexpected `&ref_0` & `*ref_0` in generated OpenAPI spec

### ISSUE THREAD

**Issue by Swimburger** [fern-api/fern#2730]
## Describe the Bug
Unexpected `&ref_0` & `*ref_0` in generated OpenAPI spec.
I don't think refs should be used in the generated spec.
 
### CLI Version
0.15.0-rc63

### Generator Version
 0.0.28

### Fern Definition

_api.yml_
```yaml
auth: ApiKey
auth-schemes:
  ApiKey:
    header: Authorization
    name: apiKey
    type: string
```

_component.yml_
```yaml

service:
  auth: true
  base-path: ""
  endpoints:
...
```

### Actual OpenAPI

```yaml
paths:
  /:
    post:
      security: &ref_0
        - ApiKeyAuth: []
    get:
      security: *ref_0
        - ApiKeyAuth: []
```

I'm not sure how it came up with the name `ApiKeyAuth`, when the specified name in Fern is `apiKey`.
