### ISSUE TITLE
[Bug] Endpoint response example `name` field is discarded

### ISSUE THREAD

**Issue by csm-kb** [fern-api/fern#2731]
Hey gang! As I was messing with our API endpoint examples and reviewing Fern docs, I realize that the `fern-openapi` generator will auto-gen `Example1`, `Example2`, and so on for response examples (clipped+trimmed example):
```yml
      examples:
        # Success response (all)
        - name: SuccessAll
          query-parameters:
            limit: 2
            start: 2
          response:
            body: $PaginatedResponseBody.example
        # Success response (single)
        - name: SuccessOneID
          query-parameters:
            id: $types.Id.example
          response:
            body: $PaginatedResponseBody.singleExample
        # Failure response
        - name: Failure
          query-parameters:
            id: $types.ApiTypeIdBase.badExample
          response:
            error: errors.IdDoesNotExistError
            body: $errors.IdDoesNotExistErrorBody.example
```
which then get reflected as selectable dropdowns in e.g. a Swagger preview for `openapi.yml` on the output.

My definition above actually includes the `name` field, which it is happy to accept -- but the OpenAPI output doesn't save that and instead replaces the name with `Example1`, `Example2`, and so on . . . like so in `openapi.yml`:
```yml
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedResponseBody'
              examples:
                Example1:
                  value:
                    # ...
```

IR does contain the fields:
```json
"examples": [
{
  "name": {
    "originalName": "SuccessAll",
    "camelCase": {
      "unsafeName": "successAll",
      "safeName": "successAll"
//...
```

Confirmed with @dsinghvi via Discord, appears to be a bug with an expected trivial fix.
