### ISSUE TITLE
[Bug] Type struct for List<object> always has omitempty in JSON marshal

### ISSUE THREAD

**Issue by csm-kb** [fern-api/fern#2738]
I found that using a `List<object>` (non-optional) type in a Fern object produces an `omitempty` for the Go type struct:
```go
key []*object `json:"<key>,omitempty"`
```
It is not currently possible to remove the `omitempty` to allow an empty array to be passed where it is expected from the user-side!

Raised to @dsinghvi, suggested that this may be a bug.

---

**Very basic Fern spec repro**
```
types:
  Object:
    properties:
      id: string
  ObjectResponseBody:
    properties:
      results: list<Object>
```
- Observe fern-go model output for `ObjectResponseBody` as
```go
type ObjectResponseBody struct {
	Results []*Object `json:"results,omitempty"`
}
```
