### ISSUE TITLE
[Feature] Improve generator configuration error messages

### ISSUE THREAD

**Issue by amckinney** [fern-api/fern#2739]
We've seen a variety of instances where users hit an error message like the following:

```
failed to read custom configuration: json: unknown field "importPath"
```

We should improve these messages so that it's more clear how the user can resolve the issue. Whether that's guessing what they're trying to do and suggest an alternative, e.g. "Did you mean to specify 'module.path'?" or simply writing out a YAML representation of the available configurations, e.g.

```
Unrecognized configuration 'importPath', please see the available configuration options below:

config:
  importPath: "path/to/generated/code"
  module:
    path: github.com/<YOUR_ORGANIZATION>/<YOUR_REPOSITORY>
    version: "<YOUR_GO_VERSION>"
  enableExplicitNull: {true,false}
```
