### ISSUE TITLE
Add a description to a Postman collection

### ISSUE THREAD

**Issue by mjpierfinance** [fern-api/fern#2751]
**Is your feature request related to a problem? Please describe.**
- It is frustrating to have to add a description manually every time I generate a new postman collection.json with fern before sharing it publicly with our end users.

**Describe the solution you'd like**
- To be able to specify the Postman collection description in the fern spec so that it is included when running `fern generate`

**Describe alternatives you've considered**
- I have been manually adding the description myself when uploading collection.json fern output to our public postman workspace. I have no other better alternative ideas currently.

**Comment by Swimburger** [comment]
This is an issue for us too. We'd rather update cosmetics like name and description in Postman and not have Fern update it, but if not possible, we can configure it in the generator.

**Comment by Swimburger** [comment]
This has been implemented in Postman generator v0.6.0. You can now specify a collection-description in your generator config:
```
groups:
  generators:
    postman:
      - name: fernapi/fern-postman
        version: 0.6.0
        config:
          collection-description: Your API description here
```

If collection-description is not set, the description will fall back to the API-level docs from your Fern definition. If neither is set, the description will be empty.
