### ISSUE TITLE
Postman generator does not plumb through examples

### ISSUE THREAD

**Issue by AmitSarah** [fern-api/fern#2755]
While generating postman from fern's generated open api spec default examples and parameters showing the data type but not the actual examples

<img width="1680" alt="Screenshot 2023-12-14 at 11 02 37 AM" src="https://github.com/fern-api/fern/assets/141001794/ea87c11a-8a21-4f16-a4f4-3351c5753125">

fern defination
accounts.yml
```
imports:
  types: ./types/accountTypes.yml
  query: ../types.yml

service:
  auth: true
  base-path: /accounting
  endpoints:
    list:
      display-name: Get All Accounts
      docs: List all Accounts
      method: POST
      path: /accounts/all
      request: getAllRequest
      response: types.GetAllAccountsResponse
      examples:
        - docs: Get all accounts
          request:
            take: 10
            skip: 0
            orderBy:
              nominal_code: asc
            filter:
              name:
                eq: "Test"
          response:
            body: $types.GetAllAccountsResponse.example

types:
  getAllRequest:
    properties:
      take: optional<integer>
      skip: optional<integer>
      orderBy: optional<AccountsOrderBy>
      filter: optional<AccountFilterFields>

  AccountsOrderBy:
    properties:
      nominal_code: optional<query.OrderBy>
      name: optional<query.OrderBy>
      category: optional<query.OrderBy>
  AccountFilterFields:
    properties:
      nominal_code: optional<query.stringOperator>
      name: optional<query.stringOperator>
      description: optional<query.stringOperator>
      category: optional<query.stringOperator>

```
accountTypes.yml

```
types:
  AccountsAllResponsesAllFields:
    properties:
      platform_id:
        docs: The ID that the accounting platform uses to identify this account
        type: string
      currency_id:
        docs: The Accounting Platform’s unique ID for the currency
        type: optional<string>
      parent_account_id:
        docs: The platform ID of the parent account
        type: optional<string>
      nominal_code:
        docs: Reference given to each account for a business. It ensures money is allocated to the correct account.
        type: optional<string>

  GetAllAccountsResponseHelper:
    properties:
      data: list<AccountsAllResponsesAllFields>

  FinalGetBankTransactionresponse:
    properties:
      data: GetAllAccountsResponseHelper

  GetAllAccountsResponse:
    extends:
      - FinalGetBankTransactionresponse
    examples:
      - name: example
        value:
          data:
            data:
              - platform_id: "1234567890123456789"
                currency_id: "3770712000000000099"
                parent_account_id: null
                nominal_code: "Rootfi 01"

```
