### ISSUE TITLE
[Feature] Support JSON fields in OpenAPI

### ISSUE THREAD

**Issue by homanp** [fern-api/fern#2760]
### Describe the bug
OpenAPI spec define json fields as below:
```
options:
          title: Options
          type: string
          format: json-string
```

Fern generates these as `Optional[str]` which makes the request fail.

### Expected behavior
Fern should be able to handle the OpenAPI spec for json fields.

### Version
Latest sdk and generators (py/ts)
