### ISSUE TITLE
Null values are automatically translated to undefined in SDK type definitions

### ISSUE THREAD

**Issue by arcticfly** [fern-api/fern#2772]
**Describe the bug**
Right now, `null` types are translated to `undefined` in the generated TypeScript SDK. We'd like to support `null` as a possible type that users of our SDK can pass in when reporting tag values, because it's more intuitive than `undefined`, and because our users currently use `null` when interfacing with our existing TypeScript SDK. Is there any way to support `null` as a possible input value?

**To Reproduce**

1. Produce an openapi.json file with a nullable value. In our case, the `tags` field is an object with string keys and values of type `string`, `number`,`boolean`, or `null`:

```
"tags": {
  "type": "object",
  "additionalProperties": {
    "anyOf": [
      {
        "type": "string",
        "nullable": true
      },
      {
        "type": "number"
      },
      {
        "type": "boolean"
      }
    ]
  },
  "description": "Extra tags to attach to the call for filtering. Eg { \"userId\": \"123\", \"promptId\": \"populate-title\" }"
}
```

2. Generate a fern TypeScript SDK from this openapi.json file.
3. Inspect your types

**Expected behavior**
The generated type definition includes `null` as potential type, e.g.

```
export declare type ReportRequestTagsValue = string | null | number | boolean;
```

**Actual behavior**
The generated type definition includes `undefined` as potential type, e.g.

```
export declare type ReportRequestTagsValue = string | undefined | number | boolean;
```

**Screenshots**

**Versions**

- Fern CLI: 0.16.33
- Generator: 0.8.13

**Additional context**
We're currently using Fern to generate our Python SDK, and it works well. We'd love to use it for our TypeScript SDK as well, but this is a blocker.

**Comment by Swimburger** [comment]
We have added support for distinguishing between null and undefined in version `47.0.0` of the Node SDK generator, see [changelog](https://github.com/fern-api/fern/blob/main/generators/typescript/sdk/CHANGELOG.md).
I suggest upgrading to the latest version of the Node SDK generator (currently `0.48.5`), then you need to enable the following option when importing your API spec.

*generators.yml*
```yaml generators.yml
api:
  specs:
    - openapi: ./openapi/openapi.json
      settings:
        respect-nullable-schemas: true
```

**Comment by nulmete-parsel** [comment]
@Swimburger I'm having a similar issue.

My setup:

```
# yaml-language-server: $schema=https://schema.buildwithfern.dev/generators-yml.json
default-group: local
groups:
  frontend:
    generators:
      - name: fernapi/fern-typescript-browser-sdk
        version: 0.6.3
        output:
          location: local-file-system
          path: ../generated/typescript
        config:
          outputEsm: true
  backend:
    generators:
      - name: fernapi/fern-openapi
        version: 0.1.7
        output:
          location: local-file-system
          path: ../generated/openapi
      - name: fernapi/fern-postman
        version: 0.4.0
        output:
          location: local-file-system
          path: ../generated/postman
```

The errors happen when I make a request from the browser to the backend and pass `addressOverride: null` for a property that's defined like this:

```
Shipment
    properties:
      # other properties...
      addressOverride: nullable<ShippingAddress>
```

Request definition:

```
ReplaceShipmentsForOrdersRequest:
    properties:
      orderIdToShipments: map<string, list<common.Shipment>>
```

note that `ShippingAddress` is a reference to another type that I've defined as well.

The error I get is the following:

```
error in openapi3filter.RequestError: request body has an error: doesn't match schema #/components/schemas/ReplaceStagedShipmentsForOrdersRequest: Error at "/orderIdToStagedShipments/gid://shopify/Order/6328377147666/0/addressOverride": Value is not nullable
```

Where should I exactly add the config lines you provided above?

```
api:
  specs:
    - openapi: ./openapi/openapi.json
      settings:
        respect-nullable-schemas: true
```
