### ISSUE TITLE
[Fern's Documentation] Document the Postman generator

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#2821]
### What can be improved

When a customer subscribes to the `Fern Docs Starter plan`, they get access to Fern's Postman integration. This allows a user to generate a Postman collection and publish it to their Postman workspace. Developers can therefore always have access to the latest Postman collection, automatically.

### Config in generators.yml

```
generators: 
  groups: 
    postman: 
     - name: fernapi/fern-postman
       version: 0.0.46
       output:
         location: postman
         api-key: ${POSTMAN_API_KEY}
         workspace-id: ${POSTMAN_WORKSPACE_ID}
       github:
         repository: imdb/imdb-postman
```

### Open in Postman

This button is popular to embed near where SDKs are mentioned in an organization's docs.

[![Open in Postman](https://run.pstmn.io/button.svg)](https://www.postman.com/fern-api/workspace/imdb-postman)

### Source code 

https://github.com/fern-api/fern/tree/main/generators/postman
