### ISSUE TITLE
OpenAPI Def Import/Export

### ISSUE THREAD

**Issue by pvpmartins** [fern-api/fern#2837]
When i do `fern init` with my openapi.yml definition, it creates for me a generators.yaml, where i insert this config:

```
default-group: local
groups:
  local:
    generators:
      - name: fernapi/fern-typescript-express
        version: 0.7.2
        output:
          location: local-file-system
          path: ./src/generated
      - name: fernapi/fern-typescript-node-sdk
        version: 0.7.2
        output:
          location: local-file-system
          path: ./src/generated
      - name: fernapi/fern-openapi
        version: 0.0.28
        config:
          format: yaml #options are yaml or json
        output:
          location: local-file-system
          path: ./
        github:
          repository: your-organization/your-repository

```

Fine, but then when i try to `fern generate -- local`

it gives me this error:
```
[api]: This workspaces has no generators.yml

```

although i just mentioned that i have opened and written in generators.yaml

Yes, my intend is to import an open api definition, generate fern definition, alter it, and export it to see if the alterations are correct
