### ISSUE TITLE
[Feature] Export openapi spec from docs

### ISSUE THREAD

**Issue by abvthecity** [fern-api/fern#2839]

**Comment by pvpmartins** [comment]
I thought it was already a feature.. I am struggling to do it. all i get is:

`[api]: This workspaces has no generators.yml`

when i add this to fern/generators.yml

```
      - name: fernapi/fern-openapi
        version: 0.0.28
        config:
          format: yaml #options are yaml or json
        output:
          location: local-file-system
          path: ./src/generated
        github:
          repository: your-organization/your-repository

```
