### ISSUE TITLE
[Bug] Using noSerdeLayer: true on Typescript Generator fails on Fern Version > 0.15.11

### ISSUE THREAD

**Issue by damonbanks** [fern-api/fern#2970]
### Describe the bug
Using noSerdeLayer: true on Typescript Generator fails on Fern Version > 0.15.11. 
Last known working version is 0.15.11

Typescript Generator: v0.9.5
Fern Version: > 0.15.11

![Screenshot 2024-02-13 at 12 44 18 PM](https://github.com/fern-api/fern/assets/149414575/c12c6e78-e296-4e82-9521-36b0b1f7a0a3)

The error specifically: `ERROR 2024-02-13T19:41:21.612Z [api]: fernapi/fern-typescript-node-sdk Property does not exist: operation`

### To reproduce

Make: 

1. Typescript Generator: v0.9.5
2. Fern Version: > 0.15.11 eg v0.17.9
3. config.noSerdeLayer: true

Attempt to generate the Typescript SDK

If relevant, provide a minimal API definition (OpenAPI or Fern Definition) or Docs configuration (`docs.yml`) that can be used to reproduce the error.

```
  preview-typescript-sdk:
    generators:
      - name: fernapi/fern-typescript-node-sdk
        version: 0.9.5
        output:
          location: npm
          package-name: "..."
          token: ${NPM_TOKEN}
        config:
          namespaceExport: "..."
          allowCustomFetcher: true
          skipResponseValidation: true
          noSerdeLayer: true
          extraDependencies:
            "@flatfile/cross-env-config": "0.0.4"
            "@types/pako": "2.0.1"
            "pako": "2.0.1"
          treatUnknownAsAny: true
```

### Expected behavior
Generator should pass with > v0.15.11 fern version

### Screenshots
![Screenshot 2024-02-13 at 12 44 18 PM](https://github.com/fern-api/fern/assets/149414575/c12c6e78-e296-4e82-9521-36b0b1f7a0a3)

### Version
Fern Version:  > 0.5.11
