### ISSUE TITLE
Go generated structs contain url annotations for every field

### ISSUE THREAD

**Issue by arcurtis** [fern-api/fern#2986]
### Describe the bug

The go model and SDK generators create structs for fern types. Each field in these structs contains a `url` annotation. These annotations are used for type safe URL param parsing in go. As far as I know, this is only useful server-side, so the SDK structs should not contain these annotations at all. These annotations are only useful in request types and so should not be in every model struct. Instead, they should be only in named `request` types.

### To reproduce
Generate any fern type, e.g.,

```
types:
  User:
    properties:
      id: string
      name: string
      email: string
```

this results in the struct:

```
type User struct {
	Id    string `json:"id" url:"id"`
	Name  string `json:"name" url:"name"`
	Email string `json:"email" url:"email"`

	_rawJSON json.RawMessage
}
```

### Expected behavior

I would expect the following struct

```
type User struct {
	Id    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`

	_rawJSON json.RawMessage
}
```

The struct `GetBar` for the following API endpoint should have the `url` annotations, however

```
service:
  base-path: /foo
  endpoints:
    get:
      method: GET
      path: /bar
      request:
        name: GetBar
        query-parameters:
          baz:
            type: string
```

### Version

Go generator 0.16.0
