### ISSUE TITLE
[Bug] Express generator fails with `Unrecognized key "whitelabel"`

### ISSUE THREAD

**Issue by anacronw** [fern-api/fern#3032]
### Describe the bug
When I run `fern generate --local`, it ends up with an error that looks like:
```
Docker exited with a non-zero exit code. Logs here: /var/folders/_9/7yr2nw5x5jd0bdycp0f5m9nm0000gq/T/tmp-35967-wCeQZTohYcjJ
```
When I cat the log, it shows:
```
cat /var/folders/_9/7yr2nw5x5jd0bdycp0f5m9nm0000gq/T/tmp-35967-wCeQZTohYcjJ

/bundle.js:15117
      throw new ParseError(parsed.errors);
            ^

ParseError: whitelabel: Unrecognized key "whitelabel"
    at Object.parseOrThrow (/bundle.js:15117:13)
    at async ExpressGeneratorCli.run (/bundle.js:260108:24)
    at async ExpressGeneratorCli.runCli (/bundle.js:260103:9) {
  errors: [
    {
      path: [ 'whitelabel' ],
      message: 'Unrecognized key "whitelabel"'
    }
  ]
}

```

### To reproduce

1. Add fern generator express:
```
      - name: fernapi/fern-typescript-express
        version: 0.7.2
        output:
          location: local-file-system
          path: ../api/src/fern

```
3. Go to fern directory
4. Run the command 'fern generate --local'
5. See error

If relevant, provide a minimal API definition (OpenAPI or Fern Definition) or Docs configuration (`docs.yml`) that can be used to reproduce the error.

### Expected behavior
I was expecting express boilerplate

### Version
Fern Version: 0.18.1

**Comment by anacronw** [comment]
bumped version to
```
default-group: local
groups:
  local:
    generators:
      - name: fernapi/fern-typescript-express
        version: 0.9.6
        output:
          location: local-file-system
          path: ../api/src/fern
        config:
          noSerdeLayer: true

```

and its working now!
