### ISSUE TITLE
fernapi/fern-typescript-browser-sdk does not generate project files

### ISSUE THREAD

**Issue by mstade** [fern-api/fern#3257]
## Describe the Bug

Output from running the TypeScript generator with output `local-file-system` does not include `package.json` and other project files. While this can be useful in so far as allowing greater project customization than the `npm` output target, it makes it much harder to keep up with things like managing the dependencies the SDK requires.

### CLI Version

`0.19.18`

### Generator Version

`fernapi/fern-typescript-browser-sdk@0.12.7`

Full `generators.yml`:

```yaml
default-group: local
groups:
  local:
    generators:
      - name: fernapi/fern-typescript-browser-sdk
        version: 0.12.7
        output:
          location: local-file-system
          path: ../generated/sdk-typescript
```

### API Definition

The minimal OpenAPI specification or Fern definition required to reproduce the bug.

```yaml
types:
  Pet:
    name: string
    age: double
```

### Actual SDK

Only source files are included.

### Expected SDK

Expected project files like `package.json` as well as the generated source code.

## Additional Context

If this behaviour is intentional, it should probably be documented here: https://docs.buildwithfern.com/generate-sd-ks/generators/type-script-node-js-sdk#local
