### ISSUE TITLE
[FR] Support Pydantic V2 without leveraging `import pydantic.v1`

### ISSUE THREAD

**Issue by Daniel-Vetter-Coverwhale** [fern-api/fern#3392]
### Describe the bug

In my python generator config I specify pydantic version v2, but still wind up with pydantic.v1 imports.

### To reproduce

Use the following generator config
```yaml
default-group: local
groups:
  local:
    generators:
      - name: fernapi/fern-python-sdk
        version: 1.1.0-rc4
        output:
          location: local-file-system
          path: ../python
        config:
          pydantic_config:
            version: v2
          client_class_name: WithterminalApi
```
Using 1.0.1 also has this issue, but I wanted to try with the latest to avoid the issue with a local unnecessary version file.

Grab any openapi you want, I'll attach one here as well.

Run fern generate. I do mine as 
`fern generat --local --log-level=debug`

Look at any of the generated classes and see that the import statement is
```python
import pydantic.v1 as pydantic
```

### Expected behavior

```python
import pydantic
```
 
### Screenshots

![image](https://github.com/fern-api/fern/assets/120594412/238db10f-e5ef-43b2-9388-332826e7d0b0)

### CLI Version

The version of the Fern CLI you are using (found in `fern.config.json`).

  "version": "0.21.0"

Uploaded as txt as github won't allow me to upload yaml 🤷 
[openapi.txt](https://github.com/fern-api/fern/files/15013527/openapi.txt)
