### ISSUE TITLE
Set allowed origins

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#364]
As a user, I want to specify a list of `origin` that my clients allow and can be expected by my servers.

**Comment by dsinghvi** [comment]
I imagine adding an `origins` field to the Fern definition that looks like: 
```yaml
origins:
  staging: https://staging.fern.com/
  prod: https://prod.fern.com/
```
Eventually this will turn into generated code that looks something like 
```typescript
const client = new Fern.Client({
  origin: Origins.Staging,
  apiKey: process.env.API_Key
)}
```
