### ISSUE TITLE
Empty extends causes fern check to fail

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#379]
```yaml
types: 
  Base: 
    properties: 
      dummy: string
  Derived: 
    extends: Base
```
fails. Instead the yaml needs to be: 
```yaml
types: 
  Base: 
    properties: 
      dummy: string
  Derived: 
    extends: Base
    properties: {}
```
