### ISSUE TITLE
Spring generator does not generate parameters for path-parameters in the base-path

### ISSUE THREAD

**Issue by ammubhave** [fern-api/fern#4139]
## Describe the Bug

For a definition which has path-parameters in the base-path, the service interface generated by the spring generator does not generate appropriate path variable arguments.

## Information to Reproduce
see below
### CLI Version

0.30.7

### Generator Version

0.9.2

### API Definition

The minimal OpenAPI specification or Fern definition required to reproduce the bug.

```yaml
service:
  auth: true
  base-path: '/foo/{fooparam}'
  path-parameters:
    fooparam: string
  endpoints:
    get:
      method: GET
      path: /bar
```

### Actual SDK

The buggy SDK that is produced:

```java
@RequestMapping(
    path = "/foo/{fooparam}"
)
public interface ... {
  @GetMapping(
      value = "",
      produces = "application/json"
  )
  ... list();
```

### Expected SDK

The expected SDK

```java
@RequestMapping(
    path = "/foo/{fooparam}"
)
public interface ... {
  @GetMapping(
      value = "",
      produces = "application/json"
  )
  ... list(@PathVariable("fooparam") String fooparam);
```
