### ISSUE TITLE
Visitor for union-of-unions does not work

### ISSUE THREAD

**Issue by ammubhave** [fern-api/fern#4140]
## Describe the Bug

The generated visitor for a union-of-unions type only visits `visitUnknown` with null values.

## Information to Reproduce

create a union of unions

### CLI Version

0.30.7

### Generator Version

0.9.2

### API Definition

The minimal OpenAPI specification or Fern definition required to reproduce the bug.

```yaml
types:
  Request: list<Operation>
  Operation:
    discriminant: op
    union:
      replace: ReplaceOperation
      add: AddOperation
  ReplaceOperation:
    discriminant: path
    union:
      '/path1': string
      '/path2': number
  AddOperation:
    discriminant: path
    union:
      '/path3': string
      '/path4': number
```

### Actual SDK

visitUnknown gets called for every operation.

### Expected SDK

Appropriate visitor methods will be called.

## Additional Context

Manually verified that the payload that client sdk is sending to spring is of the correct JSON format. It is an issue with the parser in the spring generated code
