### ISSUE TITLE
Allow flattened union-of-union generation

### ISSUE THREAD

**Issue by ammubhave** [fern-api/fern#4142]
### Problem description

If we create a union-of-unions type, the serialized JSON has the inner union nested in a `value`, instead of being flattened.

### Why would it be useful?

A very common format for PATCH REST calls is the JSON Patch (https://jsonpatch.com/). This format is currently not possible to be produced from the fern api definitions because of this additional nesting of the `value` field that happens.

E.g.
```
types:
  Request: list<Operation>
  Operation:
    discriminant: op
    union:
      replace: ReplaceOperation
      add: AddOperation
  ReplaceOperation:
    discriminant: path
    union:
      '/path1': string
      '/path2': number
  AddOperation:
    discriminant: path
    union:
      '/path3': string
      '/path4': number
```

produces serialized
```
[
  {
    op: 'replace',
    value: {
      path: '/path1',
      value: ...
    }
  }
]
```

### Describe the solution

The below should be the serialized response to conform to https://jsonpatch.com/
```
[
  {
    op: 'replace',
    path: '/path1',
    value: ...
  }
]
```
