### ISSUE TITLE
[Bug] base-properties fields do not show up in types containing them in spring generator

### ISSUE THREAD

**Issue by ammubhave** [fern-api/fern#4159]
## Describe the Bug

When union types that contain a base-property is serialized to JSON, the serialized version does not contain this field.

### CLI Version

0.36.0

### Generator Version

0.9.2

### API Definition

The minimal OpenAPI specification or Fern definition required to reproduce the bug.

```yaml
types:
  Request: list<ReplaceOperation>
  ReplaceOperation:
    base-properties:
      op: literal<"replace">
    discriminant: path
    union:
      '/path1': string
      '/path2': number
```

### Actual SDK

The buggy SDK that is produced:

```yaml
{"path":"/path1","value":"str1"},{"path":"/path2","value":123}]
```

### Expected SDK

The expected SDK

```yaml
{"op":"replace","path":"/path1","value":"str1"},{"op":"replace","path":"/path2","value":123}]
```

## Additional Context

These are primitive types used in JSON patch
