### ISSUE TITLE
Java generator generates deprecated `RequestBody.create`

### ISSUE THREAD

**Issue by ammubhave** [fern-api/fern#4194]
## Describe the Bug

Java generator is generating the deprecated method `RequestBody.create(MediaType,File)` for file endpoints.

### CLI Version

0.36.0

### Generator Version

1.0.5

### API Definition

The minimal OpenAPI specification or Fern definition required to reproduce the bug.

```yaml
endpoints:
  uploadFile:
    ...
    request:
      body:
        properties:
          file: file
```

### Actual SDK

The buggy SDK that is produced:

with`options.compilerArgs.add("-Xlint:deprecation")` on.
```
...Client.java:350: warning: [deprecation] create(MediaType,File) in RequestBody has been deprecated
      body.addFormDataPart("file", file.getName(), RequestBody.create(fileMimeTypeMediaType, file));
```

### Expected SDK

no deprecation warnings
