### ISSUE TITLE
[Bug] `application/octet-stream` response results in `None` rather than file download

### ISSUE THREAD

**Issue by krassowski** [fern-api/fern#4303]
## Describe the Bug

I struggle to find any documentation on how to download file from SDK but after some time I narrowed it down to `response: file` internal format (https://github.com/fern-api/fern/issues/1546, https://github.com/fern-api/fern/commit/0da146fd63a73a5d0d20695cc5d6bf4a27316907), which I think should correspond to OpenAPI format:

```json
"responses": {
  "200": {
    "description": "Stream the file in original format.",
    "content": {
      "application/octet-stream": {}
    }
  }
}
```

However, the generated Python code returns `None`. I know that SDK generator for Python is capable of producing an iterator on the streamed bytes:

https://github.com/fern-api/fern/blob/8fbd7084d46e2f1b5c5e1071fb9810afa710a6fe/seed/python-sdk/file-download/src/seed/service/client.py#L15

and that this is generated here:

https://github.com/fern-api/fern/blob/8fbd7084d46e2f1b5c5e1071fb9810afa710a6fe/generators/python/src/fern_python/generators/sdk/client_generator/endpoint_response_code_writer.py#L269

and I suppose that the OpenAPI parsing is defined in:

https://github.com/fern-api/fern/blob/7c2a8ea70d845d49d4af05344482878003526cee/packages/cli/openapi-parser/src/openapi/v3/converters/endpoint/convertResponse.ts#L192-L206

https://github.com/fern-api/fern/blob/7c2a8ea70d845d49d4af05344482878003526cee/packages/commons/core-utils/src/mediaType.ts#L105-L107

I do not see an obvious bug here, except for the documentation being absent. https://github.com/fern-api/fern/commit/0da146fd63a73a5d0d20695cc5d6bf4a27316907 is tagged as included since [0.16.37](https://github.com/fern-api/fern/releases/tag/0.16.37) so it does not look like a problem of using an old version, that said I do not really know this as I could not find a useful changelog.

Any hints as to why it does not work?

### CLI Version

0.22.0

### Generator Version

1.4.0-rc3

### API Definition

The minimal OpenAPI specification or Fern definition required to reproduce the bug.

```yaml
"/api/tools/file/raw-data": {
  "get": {
    "summary": "Get Raw File Data",
    "operationId": "get_raw_file_data_api_v0_tools_file_raw_data_get",
    "parameters": [
      {
        "required": true,
        "schema": {
          "title": "Document Id",
          "type": "string"
        },
        "name": "document_id",
        "in": "query"
      }
    ],
    "responses": {
      "200": {
        "description": "Stream the file in original format.",
        "content": {
          "application/octet-stream": {}
        }
      }
    },
    "x-fern-sdk-group-name": "tools",
    "x-fern-availability": "beta",
    "x-fern-audiences": ["public"],
    "x-fern-sdk-method-name": "raw_data"
  }
}
```

### Actual SDK

The buggy SDK that is produced:

```python
# client.py

def raw_data(self, *, document_id: str, request_options: typing.Optional[RequestOptions] = None) -> None: # <-------- This part is buggy
```

### Expected SDK

The expected SDK

```python
# client.py

def raw_data(self, *, document_id: str, request_options: typing.Optional[RequestOptions] = None) -> typing.Iterator[bytes]:
```

## Additional Context

None
