### ISSUE TITLE
Backticks inside links causes underline to break

### ISSUE THREAD

**Issue by zachkirsch** [fern-api/fern#4454]
If you use backticks (i.e. inline code) inside a hyperlink, the hyperlink is chunked into two pieces.

## Code

```markdown
[`/create-appointment` endpoint](/path/to/endpoint)
```

## Result

<img width="901" alt="Screenshot 2024-08-28 at 6 06 38 PM" src="https://github.com/user-attachments/assets/0a0a1d52-0e67-40b7-bedd-e544630b2cd7">

## Expected result

<img width="901" alt="Screenshot 2024-08-28 at 6 06 38 PM copy" src="https://github.com/user-attachments/assets/77eb2650-1c2b-446f-be55-7348370a6197">

## Code

I think this should be doable with:

```css
a.fern-mdx-link {
  text-decoration: none;
  position: relative;
}

a.fern-mdx-link::after {
    position: absolute;
    content: '';
    height: 1px;
    bottom: -2px;
    left: 0;
    right: 0;
    background-color: rgb(var(--accent-aa));
}
```
