### ISSUE TITLE
[Bug] allow-multiple for multi-value query params not respected by java-sdk and java-spring

### ISSUE THREAD

**Issue by shixiao** [fern-api/fern#4515]
## Describe the Bug

The allow-multiple option is not respected by the java-spring (or java sdk) generator for multi-value query params.

```
query-parameters:
  filter:
    type: string
    allow-multiple: true
```
The above definition generates `@RequestParam String filter` in the spring service interface. An example in your repo can be found [here](https://github.com/fern-api/fern/blob/main/seed/java-spring/query-parameters/.mock/definition/user.yml#L38).

## Information to Reproduce
See above

### CLI Version
0.40.4

### Generator Version

```
name: fernapi/fern-java-spring
version: 0.9.2
```

### API Definition
```
query-parameters:
  filter:
    type: string
    allow-multiple: true
```

### Actual SDK

The buggy SDK that is produced:

```java
@RequestParam String filter
```

### Expected SDK

The expected SDK

```java
@RequestParam List<String> filter
```
