### ISSUE TITLE
Override `base-path` at the endpoint level 

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#4682]
### Problem description

```yml
service: 
  endpoints: 
    get: 
      base-path: /{a}/{b}
      path: /{c}/{d}/{e}
      path-parameters: 
        a: string
        b: string
        c: string
        d: string
        e: string
```        

### Why would it be useful?

Allows folks to override the base path at the endpoint level if they don't want to override endpoint level and service level base path.
