### ISSUE TITLE
[Bug] fernapi/fern-typescript-express does not export services

### ISSUE THREAD

**Issue by adamsuskin** [fern-api/fern#4714]
## Describe the Bug

We use a monorepo with Fern, where we generate into the filesystem server bindings for Express using the `fernapi/fern-typescript-express` generator.

The API services generated are not included in the export paths following from `index.js`. This means we have to manually create another export into the package via direct source-file access, which is not ideal since our code is then dependent on the generated code folder/file structure i.e. our import for the API service looks like this:

```
import { V1Service } from "@crouton-llc/titan-api-express/src/api/resources/accounts/resources/v1/service/V1Service";
```

## Information to Reproduce

Generator config:
```
      - name: fernapi/fern-typescript-express
        version: 0.17.3
        output:
          location: local-file-system
          path: ../titan-api-express/src
```

### CLI Version

0.37.16

### API Definition

The minimal OpenAPI specification or Fern definition required to reproduce the bug.

```yaml
types:
  AccountId: uuid

  AccountProvider:
    enum:
      - google
      - microsoft
      - other

  Account:
    properties:
      id: AccountId
      name: string
      email: string
      provider: AccountProvider

  GetAccountsResponse:
    properties:
      accounts: list<Account>

service:
  auth: true
  base-path: /api/accounts/v1
  endpoints:
    getAccounts:
      docs: Get all accounts
      method: GET
      path: ""
      response: GetAccountsResponse

```

### Actual SDK

The buggy SDK that is produced:

```
import { V1Service } from "@crouton-llc/titan-api-express/src/api/resources/accounts/resources/v1/service/V1Service";
```

### Expected SDK

The expected SDK

```
import { V1Service } from "@crouton-llc/titan-api-express";
```

## Additional Context

Our package.json looks like this:

```
{
    "name": "@crouton-llc/titan-api-express",
    "private": true,
    "version": "0.1.0",
    "type": "commonjs",
    "main": "./src/index.js",
    "types": "./src/index.d.ts",
    "dependencies": {
        "express": "catalog:",
        "@types/express": "catalog:"
    },
    "exports": {
        ".": {
            "import": "./src/index.js",
            "types": "./src/index.d.ts"
        },
        "./src/*": {
            "import": "./src/*.js",
            "types": "./src/*.d.ts"
        }
    }
}
```
