### ISSUE TITLE
[Bug] fern add <generator> can unintentionally remove information

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#4716]
### Describe the bug

When I run the `fern add <generator>` command, it removes commented out code that I didn't intend for it to.

### To reproduce

Start with the following `generators.yml`
```yml 
api:
  path: openapi/openapi.json
groups:
  python-sdk:
    generators:
      - name: fernapi/fern-python-sdk
        version: 3.10.8
        # output:
        #   location: pypi
        #   package-name: "organization"
        #   token: ${PYPI_TOKEN}
        github:
          repository: fern-demo/organization-python-sdk
```

Then run `fern add fern-typescript-node-sdk --group ts-sdk`

Result:
```
api:
  path: openapi/openapi.json
groups:
  python-sdk:
    generators:
      - name: fernapi/fern-python-sdk
        version: 3.10.8
        github:
          repository: fern-demo/organization-python-sdk
  ts-sdk:
    generators:
      - name: fernapi/fern-typescript-node-sdk
        version: 0.39.3
        output:
          location: local-file-system
          path: ../sdks/typescript
```
### Expected behavior

The command should only add information, it should not restructure or remove anything that already exists.

### CLI Version

`0.42.14`
