### ISSUE TITLE
A way to specify response status-codes with void response

### ISSUE THREAD

**Issue by ammubhave** [fern-api/fern#4744]
### Problem description

Specifically for status code 204, the general convention is to have an empty body. There is no way canonical way to represent this in the fern definition. One can use optional<unknown>, or string. But then the generated sdk or server skeleton is showing incorrect meaning.

### Describe the solution (optional)

A `void`/`empty` response type. So we can say
```
response:
  type: void
  status-code: 204
```

**Comment by kbrgl** [comment]
Same use case here, this would be a great to have!

**Comment by Swimburger** [comment]
This has been supported since CLI version 0.51.12. You can declare a status code on a response without specifying a type:

```yml
service:
  auth: false
  base-path: /users
  endpoints:
    update:
      path: ""
      response:
        status-code: 204
```

By omitting the type field and only specifying status-code, the response is treated as void with the given status code. Closing this as resolved.
