### ISSUE TITLE
Module build failed: UnhandledSchemeError: Reading from "node:buffer" is not handled by plugins (Unhandled scheme) - runtime: `browser` nextjs react react-query

### ISSUE THREAD

**Issue by tresorama** [fern-api/fern#4767]
## Describe the Bug

Trying to use the generated SDK for Typescript inside a React app with Next.js in browser runtime (use client) trigger this error
```
Module build failed: UnhandledSchemeError: Reading from "node:buffer" is not handled by plugins (Unhandled scheme).
```
All working in a Server Component that use Node runtime.
Tested only in local dev.

### CLI Version

```json
{
    "organization": "xxxxx",
    "version": "0.43.5"
}
```

### Generator Version

```yml
default-group: local
groups:
  local:
    generators:
      - name: fernapi/fern-typescript-node-sdk
        version: 0.39.3
        output:
          location: local-file-system
          path: ../sdks/typescript
api:
  path: openapi/openapi.yml
```
