### ISSUE TITLE
"default" response not generated

### ISSUE THREAD

**Issue by prowave** [fern-api/fern#4786]
## Describe the Bug

When the Open API spec designated the "default" response, the api docs are stating that the endpoint returns "string" instead of the type in the "default" response.

## Information to Reproduce

```
node -v
v20.17.0
```

### CLI Version

```
fern -v
0.43.8
```

### Actual Behavior

Response
This endpoint returns a string.

### Expected Behavior

Response
This endpoint returns a list of objects.

### API Definition (if relevant)

```yaml
# Snippet that renders correct return value
"200": {
                    "description": "OK",
                    "content": {
                        "*/*": {
                            "schema": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/components/schemas/Attachment"
                                }
                            }
                        }
                    }
                }
```

```yaml
# Snippet that renders "This endpoint returns a string"
"default": {
                        "description": "default response",
                        "content": {
                            "*/*": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/Attachment"
                                    }
                                }
                            }
                        }
                    }```

## Additional Context

Swagger-UI seems to handle this properly and the OAS defintion is valid.  Changing almost 100 endpoint annotations to add `responseCode = "200"` is quite a lift.

Thanks
