### ISSUE TITLE
Add ability to hide a tab in my docs

### ISSUE THREAD

**Issue by magaldima** [fern-api/fern#4796]
### Problem description

Currently with the `TabbedNavigation`, it is impossible to hide tabs.

### Why would it be useful?

I want to use Fern to develop an entirely different API that is exposed to a different client audience than our existing one. Ideally, I want this API to only be accessible by a link so that most users who interact with our docs do not see it and get distracted.

### Describe the solution (optional)

Be able to mark tabs as hidden whereby they do not show up in the Tab Navigation bar but if i go directly to the path/slug, I can view the contents of the entire tab.

**Comment by chdeskur** [comment]
This is now supported! 

You can define a hidden tab as follows:
```
tabs:
  api:
    display-name: API Reference
  help:
    display-name: Help Center
    hidden: true
```
