### ISSUE TITLE
Light and Dark Mode for Images based on a User's Preference

### ISSUE THREAD

**Issue by timpans** [fern-api/fern#4920]
Hi team,

I would like to request a feature that allows for dynamic image selection based on the user's preference for light or dark mode when viewing documentation. Currently, while I can use the logo and background image settings, I haven't found a clear solution for selecting images from the assets folder that adapt to the chosen theme.

Here's an example of what I'm looking for:
```
<img src="/assets/ticketing/ticket-flow-light-mode.svg" alt="Light Mode" />
<img src="/assets/ticketing/ticket-flow-dark-mode.svg" alt="Dark Mode" />
```
![example-light-mode](https://github.com/user-attachments/assets/34a232e6-7fb3-469f-a8d5-319141f985d3)
![example-dark-mode](https://github.com/user-attachments/assets/004c02af-bbed-4f3b-b3be-1d0d331e97e4)

At the moment, using a single image with a fixed background doesn't fully address the issue. For example, when users switch between modes, it can look strange if the background of the image doesn't change accordingly.

A potential solution could be to use CSS with conditional classes for different modes:
```
<img src="example-light-mode.svg" class="light-mode" alt="Light Mode Image">
<img src="example-dark-mode.svg" class="dark-mode" alt="Dark Mode Image">
```

Thanks in advance!

Best,
Tim

**Comment by dannysheridan** [comment]
@chdeskur tagging you in case you have an idea about how to achieve this with the product as-is today.

**Comment by chdeskur** [comment]
We've achieved this using custom CSS. You would add something along the lines of: 
```css
:is(.light) .light-mode {
  display: block;
}

:is(.light) .dark-mode {
  display: hidden;
}

:is(.dark) .light-mode {
  display: hidden;
}

:is(.dark) .dark-mode {
  display: block;
}
```
