### ISSUE TITLE
Simplify Errors

### ISSUE THREAD

**Issue by zachkirsch** [fern-api/fern#498]
proposl:

before:
```yaml
errors:
  PostNotFoundError:
    http:
      statusCode: 404
    type:
      properties:
        id: PostId
```

after:
```yaml
errors:
  PostNotFoundError:
    statusCode: 404
    properties:
      id: PostId
```
