### ISSUE TITLE
Contrast on Inline Code Blocks Too Low

### ISSUE THREAD

**Issue by noanflaherty** [fern-api/fern#5193]
## Describe the Bug

It's hard to differentiate inline code blocks from surrounding text. The contrast is too low.

## Information to Reproduce

<img width="756" alt="2024-11-18_09-08-09" src="https://github.com/user-attachments/assets/f2744e1d-3b80-41b8-8843-0416c05558d2">

### CLI Version

`0.41.16`

### Expected Behavior

The background of the inline code block should have higher contrast (e.g. be more grey).

**Comment by awlevin** [comment]
Short-term fixed with the following:
- Add `css: ./styles.css` to `fern/docs.yml`
- Create `styles.css` in the root directory: `fern/styles.css`
- Add the following CSS rule:

```css
/* Targets only code elements with no class */
code:not([class]) {
  color: #e83e8c;
  padding: 0.2em 0.4em;
}
```
