### ISSUE TITLE
Markdown/HTML doesn't render in nested properties

### ISSUE THREAD

**Issue by nateKlaux** [fern-api/fern#5243]
## Describe the Bug

In local development, nested property descriptions fail to render Markdown/HTML formatting. Instead, they display the raw text, e.g.: 

- `[link title](link-url)` 

Notes:

- This issue occurs only for nested properties (e.g., items within an array/object).
- It doesn't render incorrectly in live documentation, but in local dev causes contributors to doubt whether their formatting is correct.

### CLI Version

"version": "0.45.0-rc52"

### Actual Behavior

<img width="533" alt="bug" src="https://github.com/user-attachments/assets/e28bdab7-6c5b-4fda-a83d-4411bb94cafd">

### Expected Behavior

<img width="567" alt="expected" src="https://github.com/user-attachments/assets/c02c16c5-9f4e-47fb-84e4-65134967bca6">

### API Definition (if relevant)

```yaml
                    customAddress:
                      type: [object, 'null']
                      description: > 
                        Description goes here.
                      properties:
                        addressName:
                          type: string
                          description: Description goes here.
                        description:
                          type: string
                          description: Description goes here.
                        categoryName: 
                          type: string
                          description: > 
                            **This property was deprecated in October 2024.**<br><br>The entity category given to the custom address when it was registered.
                          deprecated: true
```
