### ISSUE TITLE
Incorrect placeholder displayed for `null` values in a Response Example

### ISSUE THREAD

**Issue by nateKlaux** [fern-api/fern#5245]
## Describe the Bug

In Response Examples, when a property's example value is set to `null`, Fern displays a generic placeholder value instead. This results in misleading examples and will confuse customers.

### CLI Version

"version": "0.45.0-rc52"

### Actual Behavior

<img width="571" alt="bug" src="https://github.com/user-attachments/assets/0d22f8c3-b11a-4f55-a239-87cd61eb8480">

### Expected Behavior

<img width="558" alt="expected" src="https://github.com/user-attachments/assets/e53d32f9-1e4f-4dee-98c7-d9b92d7ca304">

### API Definition (if relevant)

```yaml
              examples: 
                mature-response-example:
                  summary: Mature & emerging example
                  value:
                    updatedAt: null
                    asset: "BTC"
                    assetId: null
                    network: "BITCOIN"
                    transferReference: "9f318afbad2a183f97750bc51a75b582ad8f9e9cbfb50401148857ca27cde10c:17A16QmavnUfCW11DAApiJxp7ARnxN5pGX"
                    tx: null
                    idx: null
                    usdAmount: null
                    assetAmount: null
                    timestamp: null
                    outputAddress: null
                    externalId: "393905a7-bb96-394b-9e20-3645298c1079"
```
