### ISSUE TITLE
Don't display properties marked as Deprecated in the request/response examples

### ISSUE THREAD

**Issue by nateKlaux** [fern-api/fern#5246]
## Describe the Bug

OAS 3.1.x supports a `deprecated` tag, which Fern correctly applies to the schema. However, in Response Examples, deprecated properties still appear even when they are not defined in the OAS definition. 

This results in inaccurate examples that may mislead customers.

### CLI Version

"version": "0.45.0-rc52"

### Actual Behavior

<img width="1125" alt="bug" src="https://github.com/user-attachments/assets/d8226484-3984-47af-ac96-21035e03c656">

### Expected Behavior

For properties where `deprecated: true` not to render in response examples.
<img width="552" alt="expected" src="https://github.com/user-attachments/assets/8b71d142-ab24-442b-b29a-d8bfce2d6167">

### API Definition (if relevant)

In `Example 1` below:
- The `customAddress` array is `null`, but the rendered response example still incorrectly includes `categoryName`.
- The `chainalysisIdentification` array is not `null` but does not define a `categoryName` example, yet the rendered response example still incorrectly includes `categoryName`.

```yaml
              examples:
                example1:
                  summary: Example 1
                  value:
                    - asset: ETH
                      address: "0xC8a65Fadf0e0dDAf421F28FEAb69Bf6E2E589963"
                      cluster:
                        name: "PolyNetwork Hack 2021-08-10"
                        categoryId: 6
                      rating: "lowRisk"
                      customAddress: null
                      chainalysisIdentification:
                        addressName: "STOLEN FUNDS: PolyNetwork Hack 2021-08-10"
                        description: ""
                        categoryId: 6
```
