### ISSUE TITLE
Add unsafe-union, to increase adoption

### ISSUE THREAD

**Issue by zachkirsch** [fern-api/fern#525]
```yaml
TransactionResult:
  unsafe-union:
    success: Transaction
    failure: TransactionFailure
```
