### ISSUE TITLE
Improve wrapping of latex formulas in docs

### ISSUE THREAD

**Issue by ClemMakesApps** [fern-api/fern#5346]
### CLI Version (from `fern.config.json`)

0.45.0

### Minimal API Specification

N/A

### Actual UI Behavior

We have a spot in our docs where the latex rendered formula overlaps on the right navigation links in https://docs.paradex.trade/documentation/risk-system/mark-price-calculation

![image](https://github.com/user-attachments/assets/e28e5b8c-66af-4e6e-a4db-b8aa92c586a7)

### Expected UI Behavior

Formula should wrap inside the content

**Comment by ClemMakesApps** [comment]
As a workaround, we are manually adding linebreaks in our docs: https://github.com/tradeparadex/paradex-docs/pull/40/files

**Comment by petesiki** [comment]
@ClemMakesApps can you try including a custom style.css file to your repo?  Fern has a feature that allows you to add [custom css to your docs](https://buildwithfern.com/learn/docs/building-your-docs/custom-css-global-js#custom-css) .

I tried this locally with fern's docs as an example and was able to make your formula in question above appear without overflow:
BEFORE
<img width="1333" alt="before_custom_css" src="https://github.com/user-attachments/assets/356c8d34-8303-4456-b917-05ed8253d9e5" />
AFTER
<img width="1428" alt="after_custom_css" src="https://github.com/user-attachments/assets/ecd1d394-556e-421a-a77b-227b6d78062f" />

Suggested style.css

```css
/* KaTeX formula display fixes */
.katex-display {
    /* Enable overflow wrapping */
    overflow-x: auto;
    overflow-y: hidden;
    max-width: 100%;
    padding: 0.5em 0;
}

/* Force line breaks for display math */
.katex-display > .katex {
    white-space: normal;
}

/* Handle inline math */
.katex {
    max-width: 100%;
    overflow-x: auto;
    overflow-y: hidden;
}

/* Ensure formulas don't overlap with navigation */
.katex-display .katex-html {
    max-width: calc(100% - 2em);
    overflow-x: auto;
    overflow-y: hidden;
    white-space: normal;
}

/* Optional: Add padding for better readability */
.katex-display {
    margin: 1em 0;
    padding: 0.5em 0;
}

/* Ensure formulas break at operators when needed */
.katex-display .base {
    word-break: break-word;
}

/* Handle text blocks within formulas */
.katex .text {
    word-break: break-word;
    white-space: normal;
}

/* Handle alignment environments */
.katex .align {
    display: flex;
    flex-direction: column;
    align-items: flex-start;
    max-width: 100%;
}
```

Let me know if this works for you!
