### ISSUE TITLE
`Duplicate identifier` bug from typescript browser SDK

### ISSUE THREAD

**Issue by MasterPtato** [fern-api/fern#5351]
### CLI Version from `fern.config.json`

0.45.3

### Generator & Version from `generators.yml`

fernapi/fern-typescript-browser-sdk 0.42.7

### Minimal API Specification

Structure:
```
fern
├── definition
│   ├── pkg
│   │   └── __package__.yml
│   ├── pkg2
│   │   └── __package__.yml
│   └── api.yml
├── fern.config.json
└── generators.yml
```

`pkg/__package__.yml`
```yaml
imports:
  foo2: ../pkg2/__package__.yml

types:
  Both:
    properties:
      prop1: Foo
      prop2: foo2.Foo

  Foo:
    properties:
      foo: string
```

`pkg2/__package__.yml`
```yaml
types:
  Foo:
    properties:
      foo: string
```

`api.yml`
```yaml
name: api
auth: bearer
```

`generators.yml`
```yaml
default-group: public
groups:
  public:
    generators:
      - name: fernapi/fern-typescript-browser-sdk
        version: 0.42.7
        output:
          location: local-file-system
          path: ./gen/src
```

### Actual Generated Code

`generate` command errors with
```
...

$ tsc
src/serialization/resources/pkg/types/Both.ts(8,10): error TS2300: Duplicate identifier 'Foo'.
src/serialization/resources/pkg/types/Both.ts(9,10): error TS2300: Duplicate identifier 'Foo'.

...
```

With `config.outputSourceFiles = true` the `generate` command succeeds but generates the invalid TS:

```ts
/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as FooApi from "../../../../api/index";
import * as core from "../../../../core";
import { Foo } from "./Foo";
import { Foo } from "../../pkg2/types/Foo";

export const Both: core.serialization.ObjectSchema<serializers.pkg.Both.Raw, FooApi.pkg.Both> =
    core.serialization.object({
        prop1: Foo,
        prop2: Foo,
    });

export declare namespace Both {
    interface Raw {
        prop1: Foo.Raw;
        prop2: Foo.Raw;
    }
}
```

### Expected Generated Code

Something like

```ts
/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as FooApi from "../../../../api/index";
import * as core from "../../../../core";
import { Foo as Foo } from "./Foo";
import { Foo as pkg2__Foo } from "../../pkg2/types/Foo";

export const Both: core.serialization.ObjectSchema<serializers.pkg.Both.Raw, FooApi.pkg.Both> =
    core.serialization.object({
        prop1: Foo,
        prop2: pkg2__Foo,
    });

export declare namespace Both {
    interface Raw {
        prop1: Foo.Raw;
        prop2: pkg2__Foo.Raw;
    }
}
```

### Environment Details (Optional)

Running with `npx -p fern-api fern generate --local`

Npx version: 9.6.6
Node version: v20.2.0 (the generator container seems to be using v20.18.1)
