### ISSUE TITLE
Support `x-fern-availability` OpenAPI extension on the property-level in Fern Docs

### ISSUE THREAD

**Issue by bdbyrne** [fern-api/fern#5376]
The `x-fern-availability` extension is currently supported on endpoints, however it'd be useful to support this at the propery level, namely to document which fields are beta vs. generally available.

I could imagine it'd have to look like the following to handle `$ref`s:
```yaml
some_object:
  type: object
  properties:
    field1: ...
    field2: ...
  x-fern-availability:
    field1: beta
    field2: generally-available
```

We also scope the beta tag down to enum values, if that's also an option. But field-level would be good enough for our use case.
