### ISSUE TITLE
Generator for Rust

### ISSUE THREAD

**Issue by crashdump** [fern-api/fern#5413]
### Feature Description

According to IEEE Spectrum’s 11th annual rankings of the [most popular programming languages](https://spectrum.ieee.org/top-programming-languages-2024), Rust ranks 11th and has been one of the fastest growing languages in recent years.

Frameworks like [Tauri](https://v2.tauri.app), which enable developers to write multi-platform applications while leveraging a Rust core are bound to drive this growth further.

The language is mature and well-documented in [The Cargo Book ](https://doc.rust-lang.org/cargo/index.html).

Rust's ecosystem manages packages (crates) via a tool named `Cargo`.  Ideally, Fern would be able to generate its configuration `Cargo.toml` alongside the code it generates.  For example:

```
- name: fernapi/fern-rust-sdk
  version: 0.1.0
  output:
    location: local-file-system
    path: ../sdks/rust
    config:
      cargoName: foo
      cargoDescription: bar
      cargoVersion: 1.2
```
