### ISSUE TITLE
Display `scopes` needed for endpoints per spec

### ISSUE THREAD

**Issue by jacobcovington** [fern-api/fern#5474]
### Feature Description

In the generated API docs, show which scopes are needed for an endpoint, per the provided openapi spec.

### Use Case

We have specific scopes needed for some of our endpoints, and we've specified them in our openapi schema, as described here: https://swagger.io/docs/specification/v3_0/authentication/#scopes

It would be fantastic if the docs generated with Fern picked up and displayed the scope(s) needed for specific endpoint.

Here's an example of where it's specified in our schema:
```yaml
  /v2/transaction_screening:
    get:
      summary: Check if a transaction screening exists
      operationId: checkTransactionScreening
      tags:
        - Screening
      security:
        - BearerAuth: [ "transaction_screening:read" ]
```
