### ISSUE TITLE
documentation should flow to Javadoc

### ISSUE THREAD

**Issue by brendon-** [fern-api/fern#5511]
### Issue Description

documentation in the fern api definition is lost in the java generated code.  no comments are provided.

desired:  api documentation, including relevant components and context in addiction to docs string, such as display-name, examples, etc.   This should be a markdown formatted javadoc object `///`

### Additional Context (Optional)

example generated controller route:

```yml
  base-path: '/v1/knowledge'
  endpoints:
    create_or_update_knowledge_base:
      display-name: Create or update knowledge base
      docs: Update a knowledge base or create it if it doesn't exist.
      method: PUT
      path: ''
     examples: ....
```

and generated code: 

```java
import org.springframework.web.bind.annotation.RequestMapping;

@RequestMapping(
    path = "/v1/knowledge"
)
public interface KnowledgeService {
  @PutMapping(
      value = "",
      produces = "application/json",
      consumes = "application/json"
  )
  KnowledgeBaseResponse createOrUpdateKnowledgeBase(
      @RequestHeader("X-Organization-Id") String organizationId,
      @RequestHeader("X-Agent-Id") String agentId, @RequestBody KnowledgeBaseRequest body) throws
      NotFoundError, BadRequestError, ServerError;
```
