### ISSUE TITLE
response status-code not honored in java

### ISSUE THREAD

**Issue by brendon-** [fern-api/fern#5534]
### Issue Description

```yml
      response:
        type:  void # doesn't work
        status-code: 204
```

1. there doesn't appear to be a void response allowed: `Type void is not defined.`
2. when generating the content with a trivial type to get around the missing void type:

```yml
      response:
        type:  SuccessBoolAlwaysTrue
        status-code: 204
```
it does not generate the appropriate annotations on the controller: 

expected: 
```java
@ResponseStatus(HttpStatus.NO_CONTENT)
```
but got none.
