### ISSUE TITLE
list<file> is not compilable to typescript

### ISSUE THREAD

**Issue by brendon-** [fern-api/fern#5540]
### Issue Description

using endpoint with property type: list<file> throws.

### Additional Context (Optional)

```yml
    create:
      path: 'my/path/create-with-files'
      method: POST
      request:
        name: CreateFolderWithFiles
        body:
          properties:
            folder:
              type: MyFolder
            files:
              type: list<file>
      response: MyFolder
```

this throws
``` 
[api]: fernapi/fern-typescript-node-sdk Failed to find type node with id type_mything:file
```
