### ISSUE TITLE
Give `x-fern-examples` separate fields for `sample-name` and `language`

### ISSUE THREAD

**Issue by cwcowell** [fern-api/fern#5550]
### Feature Description

We add sample code for each API operation's `x-fern-examples > code-samples` field in `openapi.yaml`. This is successfully shown to the user in a sample code box.

<img width="477" alt="image" src="https://github.com/user-attachments/assets/ea9a7d00-fcca-408a-b46a-65c66dca1a9e" />

We include 3 types of sample code in that box for each API operation, showing 3 ways of accessing that API operation:
* Make a direct API call with curl. For this sample code, we set the code sample’s `language` field to `curl`
* Make a direct API call with Python. For this sample code, we set the code sample’s `language` field to `Python API`
* Make an API call with the Python SDK. For this sample code, we set the code sample’s `language` field to `Python SDK`

This approach mostly works: we see all 3 values in the dropdown, and sample code for each shows correctly.

![2025-01-07_14-53-34 (1)](https://github.com/user-attachments/assets/2383aa75-3c71-4c7c-bf28-b8828896df8d)

The one problem we have with this approach stems from the fact that for each code sample, the `x-fern-examples > code-samples > language` field sets both the _dropdown option name_ and the _language_. The former is needed to populate the dropdown picker, and the latter is needed to figure how to do syntax highlighting for the sample code.

This means that if we set the `language` field to `Python API` or `Python SDK`, it can’t tell what language the sample code is in, so it disables syntax highlighting.

<img width="552" alt="image" src="https://github.com/user-attachments/assets/b7e12266-0c18-40e4-ab41-b8e0a8018fe1" />

To preserve syntax highlighting, we’d like a way to specify the dropdown option name separately from the language of the sample code. 

For example, maybe have these 2 fields for each piece of sample code in `openapi.yaml`:
* `x-fern-examples > code-samples > sample-name` which might be set to “Python SDK"
* `x-fern-examples > code-samples > language` which might be set to “python”

In `openapi.yaml` the proposed scheme might look like this:

```yml
      x-fern-examples:
        - code-samples:
            - sample-name: curl
              language: bash
              code: curl foo
            - sample-name: Python API
              language: python
              code: print("bar")
            - sample-name: Python SDK
              language: python
              code: print("baz")
```

### Use Case

see above

### Proposed Experience (Optional)

see above
