### ISSUE TITLE
Default values not honored in spring

### ISSUE THREAD

**Issue by brendon-** [fern-api/fern#5558]
### Issue Description

```yml

      request:
        name: SomeGetRequest
        query-parameters:
          text:
            type: boolean
            default: true
            docs: Whether to include text
```

yields

```java      
@RequestParam("text") Boolean text
````

but should yield

```java
@RequestParam(value = "text", defaultValue = "true") Boolean text
```
