### ISSUE TITLE
Custom Availability Values

### ISSUE THREAD

**Issue by aweaver89** [fern-api/fern#5596]
### Feature Description

It would be great to be able to define custom availability tags

IE
```yaml
availability:
   - type: pre-release
     title: experimental
```
     
 This would allow expanding out these labels for added clarity for users.

### Use Case

We've recently added elements to our API spec that we needed to merge to prod, but that are behind a Feature Flag.  I'd love to better indicate that these are only available to certain users with a "Closed Beta" availability tag.  It would be nice to be able to clearly indicate this to users just like we can do with callouts.
