### ISSUE TITLE
Disallow an error on an endpoint more than once

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#563]

**Comment by zachkirsch** [comment]
```yaml
myEndpoint:
  errors:
    - MyError
    - MyError
```
