### ISSUE TITLE
Global Path Parameter - Request Example Does Not Reflect Overrides

### ISSUE THREAD

**Issue by Koubek** [fern-api/fern#5841]
### Which Fern component?

Fern Docs

### How urgent is this?

P2 - Medium (Would be helpful)

### What's the issue?

Steps to reproduce:
1. Create `api.yml` with global `path-parameters`:
```
base-path: /{tenant}/{environment}/{company}
path-parameters:
  tenant: string
  environment: string
  company: string
```
2. All endpoints properly inherit these parameters, that's great and all works fine.
3. The problem came when we needed to add an exclusion and you introduced the possibility to override those global path parameters. We have one endpoint where we need just two of them.
4. Create an endpoint definition overriding the default behavior:
```
service:
  base-path: ""
  endpoints: 
    getCompanies:
      display-name: Get all companies
      # THIS IS WHERE WE OVERRIDE THE DEFAULT BEHAVIOR:
      base-path: /{tenant}/{environment}
      path: "/companies"
      path-parameters:
        tenant: string
        environment: string
      method: GET
      response: Companies
      examples:
        - path-parameters:
            tenant: bdf5f739-9e02-4e49-8006-35321e318250
            environment: production
          response:
            body:
              value:
                - id: "17ff1351-d07d-4b85-8957-b4b585f47aad"
                  systemVersion: "24.0.16410.18056"
                  name: "CRONUS International Ltd."
                  displayName: ""
                - id: "872336d7-5183-4c0b-9b47-755f3d6d77e7"
                  systemVersion: "24.0.16410.18056"
                  name: "TestCompany"
                  displayName: "TestCompany"
```
5. The previous works fine for the endpoint URL itself but the example snippet still includes the `company` segment in the URL as a parameter `{company}`:

![Image](https://github.com/user-attachments/assets/5cc7532d-a145-42d2-b075-e36bfb51a68d)

### Logs & Additional Context

We currently use `0.44.6` as #5810 blocks us using the latest versions. However, when tested using WSL I did see the same behavior. So it looks like this bug is still there.
