### ISSUE TITLE
Type Extention is not possible for unions

### ISSUE THREAD

**Issue by MahsaAbadian** [fern-api/fern#5963]
### Which Fern component?

SDK Generator

### How urgent is this?

P2 - Medium (Would be helpful)

### What's the issue?

fern does not support correct generation of a union which extends another type. When I tried this, the extension is completely ignored in the generated files.

`ConversationChartRequest` is the Union which extended `ConversationAnalyticsRequest`  but the generated types  `ConversationChartRequest`.java  and the union types such as `PieChartRequest` doesn't extend this type nor have it's field (ConversationFilter)

```
ConversationChartRequest:
  extends: ConversationAnalyticsRequest
  union:
    pie: PieChartRequest
    dateHistogram: DateHistogramRequest
    barChart: BarChartRequest

```
```
ConversationAnalyticsRequest:
    properties:
      conversationFilter:
        type: optional<ConversationFilter>

```

![Image](https://github.com/user-attachments/assets/20af14df-11eb-42ff-98ef-68c5055f7bd6)

![Image](https://github.com/user-attachments/assets/19b6c4b4-9a7f-4065-b389-4b07ada9cc5e)

### Workaround

Extend in each type under the union individually.
