### ISSUE TITLE
Add resolved types to IR

### ISSUE THREAD

**Issue by zachkirsch** [fern-api/fern#597]
```yaml
MyAlias: OtherAlias
OtherAlias: integer
...
  endpoint:
    queryParameter: MyAlias # resolves to integer
```
