### ISSUE TITLE
property of type “float” renders as “double"

### ISSUE THREAD

**Issue by cwcowell** [fern-api/fern#6074]
### Which Fern component?

Fern Docs

### How urgent is this?

P2 - Medium (Would be helpful)

### What's the issue?

1. Write an `openapi.yaml` that defines `components` / `schemas` / `sourcePage`. Within that schema, define a property called `page_number` that specifies multiple types, one of which is `type: number` and `format: float`. 
2. On the rendered page, that schema definition says the property has type “double” and not “float”.

Sample snippet from `openapi.yaml` that includes the schema described above:

```yaml
    sourcePage:
      type: object
      properties:
        page_number:
          oneOf:
            - type: integer
            - type: number
              format: float
          description: The number of the page referenced in the source document.
```

Rendered schema:

<!-- Uploading "image.png"... —>

### Workaround

none found

### Logs & Additional Context

I wonder if this is related to #5160 ?

Maybe it’s rendering “double” because it’s ignoring the `format: float` in the spec (as described in #5160), and converting the `number` type to `double`? 

Just a thought.

### Are you interested in contributing a fix?

No
