### ISSUE TITLE
Document that Fern definition service base-path can be empty string

### ISSUE THREAD

**Issue by Haakam21** [fern-api/fern#6080]
### What's the issue?

Missing content (not covered in the docs)

### URL of the documentation page (if applicable)

https://buildwithfern.com/learn/api-definition/fern/endpoints/http

### Describe the gap or issue

**Missing Content**: It is helpful to have a service base-path be "" (the empty string) in the Fern definition. But it is not well-documented that this is something one can do:
```
service:
  base-path: ""

  endpoints:
    list:
      method: GET
      path: /resource
```

### Are you interested in contributing this improvement?

Yes
