### ISSUE TITLE
Change label on Edit this Page button

### ISSUE THREAD

**Issue by sammachin** [fern-api/fern#6091]
### Which Fern component?

SDK Generator

### How important is this?

P2 - Medium (Would be helpful)

### What's the feature?

I added the edit-this-page feature as per https://buildwithfern.com/learn/docs/getting-started/global-configuration#github-configuration

I'd like to change the label on that button to say something like "Improve this page: rather than edit, 
Ideally this would be implemented as a config param for something like lable under the edit-this-page config

### Are you interested in contributing this feature?

Yes

**Comment by sammachin** [comment]
I'd just go with something like:
```
instances:
  - url: plantstore.docs.buildwithfern.com
    edit-this-page:
      label: Improve this page
      github: 
        owner: fern
        repo: plant-store-docs
        branch: main
```
