### ISSUE TITLE
When an env variable is used for the API key, include it in the SDK docs

### ISSUE THREAD

**Issue by jcbwndsr** [fern-api/fern#6206]
### Which Fern component?

SDK Generator

### How important is this?

P0 - Critical (Blocking work)

### What's the feature?

**Feature** Include env variable usage in the API key docs
**Why?** So that users of the generated SDK know that they can use the docs

**Description**
Now, when an environment variable is allowed for setting the client, API key, it is undocumented in the generated README.

generators.yml
```yaml
...
auth-schemes:
  ApiKeyAuthScheme:
    header: X-API-Key
    type: string
    name: apiKey
    env: PLANTS_API_KEY  
...
```

resulting README.md:
```python
from axiomatic import Axiomatic, UserRequirement

client = Axiomatic(
    api_key="YOUR_API_KEY",
)
```

**Suggested README addition to "usage" section**
```markdown
### Environment Variable
You may also set the API key via an environment variable:

```python
from axiomatic import Axiomatic, UserRequirement
import os

os.environ["PLANTS_API_KEY"] = "YOUR_API_KEY"

client = Axiomatic()
```

### Are you interested in contributing this feature?

Can do!
