### ISSUE TITLE
Change the word "alias" to "type"

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#626]
When creating a type, the property `alias` should be renamed to `type`. 

from:
```
types:
     myId:
          alias: LaptopId
          docs: This is a laptop.
```

to:
```
types:
     myId:
          type: LaptopId
          docs: This is a laptop.
```
