### ISSUE TITLE
Validation Rule: Property reuse in query and path param

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#627]
Warn when the same property is used as a query-parameter and path-parameter on an endpoint.

e.g.
```
myEndpoint:
     path: /{id}
     method: GET
     path-parameters:
          id: myId
     query-parameters:
          id: yourId
```
