### ISSUE TITLE
Nullable params do not work when not all specs define it

### ISSUE THREAD

**Issue by artem-vereshchaka** [fern-api/fern#6408]
### Which Fern component?

SDK Generator

### How urgent is this?

P2 - Medium (Would be helpful)

### What's the issue?

When `respect-nullable-schemas` is set for a single spec, generator doesn't respect it.

generators.yml is
```yaml
# yaml-language-server: $schema=https://schema.buildwithfern.dev/generators-yml.json
groups:
  admin:
    audiences:
      - admin
    generators:
      - name: fernapi/fern-typescript-node-sdk
        version: 0.48.7
        config:
          inlineFileProperties: true
          skipResponseValidation: true
          namespaceExport: Platform
        output:
          ...
        github:
          ...
  internal:
    audiences:
      - internal
    generators:
      - name: fernapi/fern-typescript-node-sdk
        version: 0.48.7
        config:
          inlineFileProperties: true
          skipResponseValidation: true
          namespaceExport: Platform
        output:
          ...
        github:
          ...
  public:
    audiences:
      - public
    generators:
      - name: fernapi/fern-typescript-node-sdk
        version: 0.48.7
        config:
          inlineFileProperties: true
          skipResponseValidation: true
          namespaceExport: Platform
        output:
          ...
        github:
          ...
      - name: fernapi/fern-java-sdk
        config:
          client-class-name: Platform
        version: 2.18.1
        output:
          ...
        github:
          ...

auth-schemes:
  Bearer:
    scheme: bearer

api:
  auth: Bearer
  headers:
    x-caller:
      type: string
      name: caller
  specs:
    - openapi: ../services/foo/app/openapi.yaml
      namespace: foo
    - openapi: ../services/bar/app/openapi.yaml
      settings:
        default-form-parameter-encoding: form
      namespace: bar
    - openapi: ../services/baz/openapi.yaml
      namespace: baz
      settings:
        respect-nullable-schemas: true
  environments:
    Production:
      urls:
        ...
    Development:
      urls:
        ...
```

If the setting is enabled for **every** spec -- generator works as expected and exposes proper nulls in the interfaces.

### Fern CLI & Generator Versions

CLI version: 0.56.5
Generator version: fernapi/fern-typescript-node-sdk@0.48.7

### Workaround

Setting the `respect-nullable-schemas` for every spec solves the issue, but it might be not expected behaviour since specs are different.

Also, it would be nice to have the setting on the global level, not per spec.

### Are you interested in contributing a fix?

No
