### ISSUE TITLE
Can't use resources outside of the fern/assets folder

### ISSUE THREAD

**Issue by paskahlisanjas** [fern-api/fern#6452]
### How urgent is this?

P2 - Medium (Would be helpful)

### Step to Reproduce
1. Put references to assets outside of the `fern/assets` folder in `docs.yaml`, for example:
```yaml
...
favicon: ../web/public/favicon.ico
logo:
  dark: ../web/public/company-logo.svg
typography:
  headingsFont:
    name: Heading Font
    path: ../web/public/fonts/heading-font.woff
  bodyFont:
    name: Body Font
    path: ../web/public/fonts/body-font.woff
...
```
2. Try running one of these commands:
```sh
fern generate --docs --preview
# or
fern generate --docs
```

**Expected result**: the assets are uploaded and docs are generated
**Actual result**: errors with 403 code
```
...
[docs]: Failed to upload /absolute/path/to/the-file-referenced.svg
[docs]: Request failed with status code 403
...
```

### Fern CLI & Generator Versions

Fern CLI Version: `0.56.20`
Fern SDK Generator Version: `fernapi/fern-typescript-node-sdk` (`0.48.7`)

### Workaround

Putting all the necessary assets inside the `fern/assets`
