### ISSUE TITLE
Independent navigation in `docs.yml` across instances

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#6491]
### Which Fern component?

Fern Docs

### How important is this?

P2 - Medium (Would be helpful)

### What's the feature?

If a user wants to publish 5 independent docs sites at different URLs, there should be a way of associating content specifically to an instance. 

## Option 1: Add `instance` filters in `docs.yml` 

```yml
instances: 
  alpha: 
    url: alpha.docs.buildwithfern.com
  beta: 
    url: beta.docs.buildwithfern.com

navigation: 
  - section: My Alpha Section
    instance: 
      - alpha
    contents: ...
```

Any nested navigation key like `tab`, `page`, `api` would have an `instance` that allows you to associate specific navigation items with that instance. While this works, this could be quite confusing to maintain if the navigation starts to get large. 

## Option 2: An instance can have its own navigation

```yml
instances: 
  alpha: 
    url: alpha.docs.buildwithfern.com
    navigation: alpha/navigation.yml
  beta: 
    url: beta.docs.buildwithfern.com
    navigation: alpha/navigation.yml
```

In this mode, you can define the navigation for a particular instance (if you want) and it is not shared across the two. 

### Are you interested in contributing this feature?

No
