### ISSUE TITLE
Support loading MDX files from a separate repo in docs.yml

### ISSUE THREAD

**Issue by dsinghvi** [fern-api/fern#6499]
### Which Fern component?

SDK Generator

### How important is this?

P1 - High (Strongly needed)

### What's the feature?

My docs website references Markdown files that live at a different URL: 
```yml
navigation: 
- page: My Page
  path: https://github.com/path/to/some/mdx

```

### Are you interested in contributing this feature?

No
