### ISSUE TITLE
Nested generics

### ISSUE THREAD

**Issue by ethansorkin** [fern-api/fern#6530]
### How important is this?

P2 - Medium (Would be helpful)

### What's the feature?

It would be great for generics to allow multiple layers of nesting so we can define top level request/response shapes than can pass down nested attributes. Currently I have only seen generics working 1 level deep, which is not very helpful for consolidating our schema definitions, which all follow the same top level structure. Ideally it could look something like this, where we would have a reusable request/response wrapper:

```
Request<T>:
  properties:
    data: list<Data<T>>

Data<T>:
  properties:
    id: string
    type: string
    attributes: T

User:
  properties:
    name: string
    userId: string
    zipCode: optional<string>
```

Then the request type of my CreateUsers endpoint would be `Request<User>`

**Comment by Swimburger** [comment]
This is now supported as of CLI v3.91.0 (merged in [fern#12917](https://github.com/fern-api/fern/pull/12917)).

Generic type properties that reference other generic types now correctly substitute parameters throughout the type reference string. For example:

```yml
Data<T>:
  properties:
    id: string
    type: string
    attributes: T
 
Request<T>:
  properties:
    data: list<Data<T>>
 
CreateUsersRequest:
  type: Request<User>
```

CreateUsersRequest will correctly expand data to list<Data<User>>, with Data<User> further resolving attributes to User.

This also works with multi-param generics, optional wrappers, and arbitrarily nested generic expressions
