### ISSUE TITLE
Allowing multiple values in `x-fern-sdk-method-name`

### ISSUE THREAD

**Issue by chiragjn** [fern-api/fern#6581]
### Which Fern component?

SDK Generator

### How important is this?

P3 - Low (Nice to have)

### What's the feature?

In some cases there can be requirements to have aliasing for the same method name. One such example is having a PUT api that handles both create and update

It would be nice to have something like

```
paths:
  /v1/users:
    put:
      x-fern-sdk-group-name: ["v1", "users"]
      x-fern-sdk-method-name: ["create", "update"]
```

leading to 

```
client.v1.users.create(...)
client.v1.users.update(...)
```

instead of 

```
paths:
  /v1/users:
    put:
      x-fern-sdk-group-name: ["v1", "users"]
      x-fern-sdk-method-name: create_or_update
```

```
client.v1.users.create_or_update(...)
```

### Are you interested in contributing this feature?

No
