### ISSUE TITLE
Inline request parameters do not respect optional field

### ISSUE THREAD

**Issue by aryehklein** [fern-api/fern#6982]
### Which Fern component?

SDK Generator

### How urgent is this?

P0 - Critical (Blocking work)

### What's the issue?

My fern definition is defined as:
```
  endpoints:
    CreateSourceMedia:
      method: POST
      path: /{system_id}/source-media
      path-parameters:
        system_id: uuid
      request:
        name: CreateSourceMediaRequest
        body:
          properties:
            name: string
            description: string
            file: file
            metadata: optional<map<string, string>>
```
When I make a call to the endpoint without passing metadata in, I get:
```
{
    "detail": [
        {
            "type": "missing",
            "loc": [
                "body",
                "metadata"
            ],
            "msg": "Field required",
            "input": null
        }
    ]
}
```
This is unexpected as metadata is optional. Looking into the generated fern code, the error comes from:
```
 def __init_create_source_media(cls, router: fastapi.APIRouter) -> None:
        endpoint_function = inspect.signature(cls.create_source_media)
        new_parameters: typing.List[inspect.Parameter] = []
        for index, (parameter_name, parameter) in enumerate(
            endpoint_function.parameters.items()
        ):
            if index == 0:
                new_parameters.append(parameter.replace(default=fastapi.Depends(cls)))
            elif parameter_name == "name":
                new_parameters.append(parameter.replace(default=fastapi.Body(...)))
            elif parameter_name == "description":
                new_parameters.append(parameter.replace(default=fastapi.Body(...)))
            elif parameter_name == "file":
                new_parameters.append(parameter.replace(default=fastapi.UploadFile))
            elif parameter_name == "metadata":
                new_parameters.append(parameter.replace(default=fastapi.Body(...)))
            elif parameter_name == "system_id":
                new_parameters.append(parameter.replace(default=fastapi.Path(...)))
            elif parameter_name == "auth":
                new_parameters.append(
                    parameter.replace(default=fastapi.Depends(FernAuth))
                )
            else:
                new_parameters.append(parameter)
        setattr(
            cls.create_source_media,
            "__signature__",
            endpoint_function.replace(parameters=new_parameters),
        )
```
Specifically, 
```
elif parameter_name == "metadata":
                new_parameters.append(parameter.replace(default=fastapi.Body(...)))
```
If I switch this to default=fastapi.Body(None) the error goes away, and similarly, I dont see the same issue for optional fields defined as part of a type object - in that case the optional fields arent mentioned at all in the fern init functions. As this is a form upload api (Which currently has to be defined as an inline request for some reason), this essentially means we cant support optional fields in these cases.

### Fern CLI & Generator Versions

fern.version=0.56.25
fern.python.api.version="1.6.3"
fern.python.sdk.version="4.3.18"

### Are you interested in contributing a fix?

No
