### ISSUE TITLE
Python circular reference errors from subclassed Pydantic models with forward references

### ISSUE THREAD

**Issue by hughhan1** [fern-api/fern#7026]
### Which Fern component?

SDK Generator

### How urgent is this?

P2 - Medium (Would be helpful)

### What's the issue?

Consider the following Fern API definition.
```yml
types:
  FirstUnion:
    discriminated: false
    union: 
      - FirstUnionFirstElement
      - FirstUnionSecondElement
  SecondUnion:
    discriminated: false
    union:
      - SecondUnionFirstElement
      - SecondUnionSecondElement
  FirstUnionFirstElement:
    properties:
      child: SecondUnion
  FirstUnionSecondElement:
    properties:
      child: SecondUnion
  SecondUnionFirstElement:
    properties:
      child: FirstUnion
  SecondUnionSecondElement:
    extends: 
      - SecondUnionSecondElementSuperclass
  SecondUnionSecondElementSuperclass:
    properties:
      child: FirstUnion
  ContainerValue:
    union:
      list: list<FieldValue>
      optional: optional<FieldValue>
  PrimitiveValue:
    enum:
      - STRING
      - NUMBER
  ObjectValue:
    properties: {}
  FieldName: string
  FieldValue:
    union:
      primitive_value: PrimitiveValue
      object_value: ObjectValue
      container_value: ContainerValue
  ObjectFieldValue:
    docs: This type allows us to test a circular reference with a union type (see FieldValue).
    properties:
      name: FieldName
      value: FieldValue
```
This generates the following code in Python.
```python
# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from .second_union_second_element_superclass import SecondUnionSecondElementSuperclass


class SecondUnionSecondElement(SecondUnionSecondElementSuperclass):
    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
```
```python
# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel, update_forward_refs


class SecondUnionSecondElementSuperclass(UniversalBaseModel):
    child: "FirstUnion"

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from .first_union_first_element import FirstUnionFirstElement  # noqa: E402, F401, I001
from .first_union_second_element import FirstUnionSecondElement  # noqa: E402, F401, I001
from .second_union_first_element import SecondUnionFirstElement  # noqa: E402, F401, I001
from .second_union_second_element import SecondUnionSecondElement  # noqa: E402, F401, I001
from .first_union import FirstUnion  # noqa: E402, F401, I001

update_forward_refs(SecondUnionSecondElementSuperclass)
```
This causes the following error.
```
ImportError while importing test module '/circular-references-advanced/generated/tests/utils/test_http_client.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/utils/test_http_client.py:3: in <module>
    from seed.core.http_client import get_request_body
src/seed/__init__.py:6: in <module>
    from . import a, ast
src/seed/ast/__init__.py:5: in <module>
    from .types import (
src/seed/ast/types/__init__.py:9: in <module>
    from .first_union_first_element import FirstUnionFirstElement
src/seed/ast/types/first_union_first_element.py:24: in <module>
    from .first_union_second_element import FirstUnionSecondElement  # noqa: E402, F401, I001
src/seed/ast/types/first_union_second_element.py:25: in <module>
    from .second_union_first_element import SecondUnionFirstElement  # noqa: E402, F401, I001
src/seed/ast/types/second_union_first_element.py:26: in <module>
    from .second_union_second_element import SecondUnionSecondElement  # noqa: E402, F401, I001
src/seed/ast/types/second_union_second_element.py:7: in <module>
    from .second_union_second_element_superclass import SecondUnionSecondElementSuperclass
src/seed/ast/types/second_union_second_element_superclass.py:27: in <module>
    from .second_union_second_element import SecondUnionSecondElement  # noqa: E402, F401, I001
E   ImportError: cannot import name 'SecondUnionSecondElement' from partially initialized module 'seed.ast.types.second_union_second_element' (most likely due to a circular import) (/circular-references-advanced/generated/src/seed/ast/types/second_union_second_element.py)
```

### Are you interested in contributing a fix?

Yes
