### ISSUE TITLE
Pydantic "not fully defined" errors for containerized forward references

### ISSUE THREAD

**Issue by hughhan1** [fern-api/fern#7063]
### Which Fern component?

SDK Generator

### How urgent is this?

P1 - High (Strongly needed)

### What's the issue?

Consider the following Fern definition.
```yml
types:
  Node:
    discriminated: false
    union:
      - BranchNode
      - LeafNode
  BranchNode:
    properties:
      children: list<Node>
  LeafNode:
    properties: {}
  NodesWrapper:
    properties:
      nodes: list<list<Node>>
```

Running the Python SDK generator produces the following code.
##### nodes_wrapper.py
```python
import typing

from ...core.pydantic_utilities import UniversalBaseModel
from .node import Node

class NodesWrapper(UniversalBaseModel):
    nodes: typing.List[typing.List[Node]]
    ...
```
##### node.py
```python
import typing

from .leaf_node import LeafNode

if typing.TYPE_CHECKING:
    from .branch_node import BranchNode
Node = typing.Union["BranchNode", LeafNode]
```
However, note that `Node` contains a forward reference, but no invocation to `update_forward_refs(NodesWrapper)` is generated after the `NodesWrapper` class definition. Hence, when attempting to instantiate `NodesWrapper(...)`, the following error is received.
```
pydantic.errors.PydanticUserError: `NodesWrapper` is not fully defined; you should define `BranchNode`, then call `NodesWrapper.model_rebuild()`.
```

The proper code to be generated would be the following.
##### nodes_wrapper.py
```python
import typing

from ...core.pydantic_utilities import UniversalBaseModel, update_forward_refs

class NodesWrapper(UniversalBaseModel):
    nodes: typing.List[typing.List["Node"]]
    ...

from .branch_node import BranchNode
from .node import Node

update_forward_refs(NodesWrapper)
```

### Fern CLI & Generator Versions

SDK Generator versions:
- fernapi/fern-python-sdk v4.18.4

### Workaround
The following are examples of workarounds for specific versions of this problem:
* https://github.com/elevenlabs/elevenlabs-python/pull/528
* https://github.com/vectara/python-sdk/pull/49

### Are you interested in contributing a fix?

Yes
