### ISSUE TITLE
Add fern-check rule to prevent "hard dependencies" between circular imports

### ISSUE THREAD

**Issue by zachkirsch** [fern-api/fern#729]
Fern should allow intra-file circular dependencies in some cases: When (1) there's a container used to prevent an infinite loop:

```yaml
types:
  A:
    properties:
      b: B
      c: C
      d: D
  B: optional<A>
  C:
    properties:
      optionalA: optional<A>
      listA: list<A>
      setA: list<A>
```

or (2) there's a union that allows "escaping" into another type:

```yaml
  D:
    union:
      a: A
      somethingBesidesA: {}
```

Outside of those cases, intra-file circular dependencies should not be allowed:

```yaml
types:
  A:
    properties:
      b: b
      c: C
  B: A # not allowed
  C:
    extends: A # not allowed
    properties:
      a: A # not allowed
  D:
    union:
      a: A
      # not allowed because no other choice but for D to contain an A
```
