### ISSUE TITLE
Allow export as a type name

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#757]
```
types:
  Export:
    properties:
      name:
        type: string
```

Right now, this fails with "NotImplementedError: Unexpected! Inserting syntax kind of ModuleDeclaration, but ExpressionStatement was inserted."
