### ISSUE TITLE
Query parameter names should be required when wire value is not valid for codegen

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#768]
```
query-parameters:
            since: 
              type: optional<datetime>
              docs: Returns only audit trails created after this date (UTC and in ISO8601 Format - YYYY-MM-DDTHH:MM:SS.SSSZ)
            page[number]: 
              name: pageNumber
              type: integer
              docs: If omitted, the endpoint will return the first page.
```
