### ISSUE TITLE
Support global headers

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#874]
As a user, I can specify a header (e.g. X-Api-Version)

```yaml
global-headers: 
  X-Api-Version: 
     type: string 
```

This would generate the following TypeScript code:

```typescript
const client = new Client({
  "X-Api-Version": 2.2
})
```
