### ISSUE TITLE
Document availability

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#875]
```yaml
endpoints:
    myEndpoint:
        availability: pre-release
        method: GET 
        path: /endpoint
        response: EndpointResponse
```
