### ISSUE TITLE
Customize the credential parameters in the SDK

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#891]
Ask: allow config to set `username` and `password` to custom fields.

```javascript
const client = new AcmeApiClient({
  environment: 'Production',
  auth: {
    credentials: {
      username: 'my-username',
      password: 'my-password',
    },
  },
});
```

**Comment by dannysheridan** [comment]
wants:

const client = new AcmeApiClient({
  environment: 'Production',
  auth: {
    credentials: {
      client_ID: 'my-client-id',
      secret: 'my-secret',
    },
  },
});

**Comment by dsinghvi** [comment]
```
auth: 
  type: basic
  username:
    name: clientId
  password: 
    name: secret
```
@zachkirsch something like that? or do you think it goes under `auth-schems` instead?
