### ISSUE TITLE
auth-schemes should support docs

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern#905]
In this example
```
auth-schemes: 
  access_key: 
    header: access_key
    name: accessKey
    docs: Unique access key provided by {company} for each authorized user.
```

I get this response from `fern check`
```
Failed to parse file: fern/api/definition/api.yml
  - Unrecognized key(s) in object: 'docs' at "auth-schemes.access_key"
 ```
