### ISSUE TITLE
Add inline request bodies to YAML

### ISSUE THREAD

**Issue by zachkirsch** [fern-api/fern#968]
Summary:
  1. We're adding the ability to declare request bodies inline with the endpoint, rather than needing to declare a separate type for the request body.
  2. If the SDK will generate a ["request wrapper"](https://github.com/fern-api/fern/issues/966), then the user must specify a "request wrapper name" in the YAML

Motivation:
- https://github.com/fern-api/fern/issues/966 
- https://github.com/fern-api/fern/issues/967

Plan:

```yaml
...
endpoints:
  setUser:
    path: /users/{userId}
    request:
      name: SetUserRequest # this is the name of the request wrapper
      path-parameters:
        userId: string
      query-parameters:
        ...
      headers:
        ...
      body: # can also do body: <name of type>
        extends: ...
        properties: ...
```
